/// Contracts for response
const String contractForResponse = '''
{
  "contracts_for": {
    "available": [
      {
        "barrier_category": "asian",
        "barriers": 0,
        "contract_category": "asian",
        "contract_category_display": "Asians",
        "contract_display": "Asian Up",
        "contract_type": "ASIANU",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "synthetic_index",
        "max_contract_duration": "10t",
        "min_contract_duration": "5t",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "asian",
        "barriers": 0,
        "contract_category": "asian",
        "contract_category_display": "Asians",
        "contract_display": "Asian Down",
        "contract_type": "ASIAND",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "synthetic_index",
        "max_contract_duration": "10t",
        "min_contract_duration": "5t",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "Higher",
        "contract_type": "CALL",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "market": "synthetic_index",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "Lower",
        "contract_type": "PUT",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "market": "synthetic_index",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier": "7556.9932",
        "barrier_category": "euro_non_atm",
        "barriers": 1,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "Higher",
        "contract_type": "CALL",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "market": "synthetic_index",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier": "7556.9932",
        "barrier_category": "euro_non_atm",
        "barriers": 1,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "Lower",
        "contract_type": "PUT",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "market": "synthetic_index",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "Higher",
        "contract_type": "CALL",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "forward_starting_options": [
          {
            "close": "1588809599",
            "date": "1588723200",
            "open": "1588723200"
          },
          {
            "close": "1588895999",
            "date": "1588809600",
            "open": "1588809600"
          },
          {
            "close": "1588982399",
            "date": "1588896000",
            "open": "1588896000"
          }
        ],
        "market": "synthetic_index",
        "max_contract_duration": "1d",
        "min_contract_duration": "2m",
        "sentiment": "up",
        "start_type": "forward",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "Lower",
        "contract_type": "PUT",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "forward_starting_options": [
          {
            "close": "1588809599",
            "date": "1588723200",
            "open": "1588723200"
          },
          {
            "close": "1588895999",
            "date": "1588809600",
            "open": "1588809600"
          },
          {
            "close": "1588982399",
            "date": "1588896000",
            "open": "1588896000"
          }
        ],
        "market": "synthetic_index",
        "max_contract_duration": "1d",
        "min_contract_duration": "2m",
        "sentiment": "down",
        "start_type": "forward",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "Higher",
        "contract_type": "CALL",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "synthetic_index",
        "max_contract_duration": "1d",
        "min_contract_duration": "15s",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "Lower",
        "contract_type": "PUT",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "synthetic_index",
        "max_contract_duration": "1d",
        "min_contract_duration": "15s",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier": "+2.1454",
        "barrier_category": "euro_non_atm",
        "barriers": 1,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "Higher",
        "contract_type": "CALL",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "synthetic_index",
        "max_contract_duration": "1d",
        "min_contract_duration": "15s",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier": "+2.1454",
        "barrier_category": "euro_non_atm",
        "barriers": 1,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "Lower",
        "contract_type": "PUT",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "synthetic_index",
        "max_contract_duration": "1d",
        "min_contract_duration": "15s",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "Higher",
        "contract_type": "CALL",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "synthetic_index",
        "max_contract_duration": "10t",
        "min_contract_duration": "1t",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "Lower",
        "contract_type": "PUT",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "synthetic_index",
        "max_contract_duration": "10t",
        "min_contract_duration": "1t",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier": "+1.2385",
        "barrier_category": "euro_non_atm",
        "barriers": 1,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "Higher",
        "contract_type": "CALL",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "synthetic_index",
        "max_contract_duration": "10t",
        "min_contract_duration": "5t",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier": "+1.2385",
        "barrier_category": "euro_non_atm",
        "barriers": 1,
        "contract_category": "callput",
        "contract_category_display": "Up/Down",
        "contract_display": "Lower",
        "contract_type": "PUT",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "synthetic_index",
        "max_contract_duration": "10t",
        "min_contract_duration": "5t",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callputequal",
        "contract_category_display": "Rise/Fall Equal",
        "contract_display": "Higher",
        "contract_type": "CALLE",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "market": "synthetic_index",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callputequal",
        "contract_category_display": "Rise/Fall Equal",
        "contract_display": "Lower",
        "contract_type": "PUTE",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "market": "synthetic_index",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callputequal",
        "contract_category_display": "Rise/Fall Equal",
        "contract_display": "Higher",
        "contract_type": "CALLE",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "forward_starting_options": [
          {
            "close": "1588809599",
            "date": "1588723200",
            "open": "1588723200"
          },
          {
            "close": "1588895999",
            "date": "1588809600",
            "open": "1588809600"
          },
          {
            "close": "1588982399",
            "date": "1588896000",
            "open": "1588896000"
          }
        ],
        "market": "synthetic_index",
        "max_contract_duration": "1d",
        "min_contract_duration": "2m",
        "sentiment": "up",
        "start_type": "forward",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callputequal",
        "contract_category_display": "Rise/Fall Equal",
        "contract_display": "Lower",
        "contract_type": "PUTE",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "forward_starting_options": [
          {
            "close": "1588809599",
            "date": "1588723200",
            "open": "1588723200"
          },
          {
            "close": "1588895999",
            "date": "1588809600",
            "open": "1588809600"
          },
          {
            "close": "1588982399",
            "date": "1588896000",
            "open": "1588896000"
          }
        ],
        "market": "synthetic_index",
        "max_contract_duration": "1d",
        "min_contract_duration": "2m",
        "sentiment": "down",
        "start_type": "forward",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callputequal",
        "contract_category_display": "Rise/Fall Equal",
        "contract_display": "Higher",
        "contract_type": "CALLE",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "synthetic_index",
        "max_contract_duration": "1d",
        "min_contract_duration": "15s",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callputequal",
        "contract_category_display": "Rise/Fall Equal",
        "contract_display": "Lower",
        "contract_type": "PUTE",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "synthetic_index",
        "max_contract_duration": "1d",
        "min_contract_duration": "15s",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callputequal",
        "contract_category_display": "Rise/Fall Equal",
        "contract_display": "Higher",
        "contract_type": "CALLE",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "synthetic_index",
        "max_contract_duration": "10t",
        "min_contract_duration": "1t",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "euro_atm",
        "barriers": 0,
        "contract_category": "callputequal",
        "contract_category_display": "Rise/Fall Equal",
        "contract_display": "Lower",
        "contract_type": "PUTE",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "synthetic_index",
        "max_contract_duration": "10t",
        "min_contract_duration": "1t",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "non_financial",
        "barriers": 1,
        "contract_category": "digits",
        "contract_category_display": "Digits",
        "contract_display": "Digit Matches",
        "contract_type": "DIGITMATCH",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "last_digit_range": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9
        ],
        "market": "synthetic_index",
        "max_contract_duration": "10t",
        "min_contract_duration": "1t",
        "sentiment": "match",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "non_financial",
        "barriers": 1,
        "contract_category": "digits",
        "contract_category_display": "Digits",
        "contract_display": "Digit Differs",
        "contract_type": "DIGITDIFF",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "last_digit_range": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9
        ],
        "market": "synthetic_index",
        "max_contract_duration": "10t",
        "min_contract_duration": "1t",
        "sentiment": "differ",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "non_financial",
        "barriers": 0,
        "contract_category": "digits",
        "contract_category_display": "Digits",
        "contract_display": "Digit Odd",
        "contract_type": "DIGITODD",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "synthetic_index",
        "max_contract_duration": "10t",
        "min_contract_duration": "1t",
        "sentiment": "odd",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "non_financial",
        "barriers": 0,
        "contract_category": "digits",
        "contract_category_display": "Digits",
        "contract_display": "Digit Even",
        "contract_type": "DIGITEVEN",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "synthetic_index",
        "max_contract_duration": "10t",
        "min_contract_duration": "1t",
        "sentiment": "even",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "non_financial",
        "barriers": 1,
        "contract_category": "digits",
        "contract_category_display": "Digits",
        "contract_display": "Digit Over",
        "contract_type": "DIGITOVER",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "last_digit_range": [
          0,
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8
        ],
        "market": "synthetic_index",
        "max_contract_duration": "10t",
        "min_contract_duration": "1t",
        "sentiment": "over",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "non_financial",
        "barriers": 1,
        "contract_category": "digits",
        "contract_category_display": "Digits",
        "contract_display": "Digit Under",
        "contract_type": "DIGITUNDER",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "last_digit_range": [
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9
        ],
        "market": "synthetic_index",
        "max_contract_duration": "10t",
        "min_contract_duration": "1t",
        "sentiment": "under",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "euro_non_atm",
        "barriers": 2,
        "contract_category": "endsinout",
        "contract_category_display": "Ends Between/Ends Outside",
        "contract_display": "Ends Outside",
        "contract_type": "EXPIRYMISS",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "high_barrier": "7556.9932",
        "low_barrier": "7231.3151",
        "market": "synthetic_index",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "high_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "euro_non_atm",
        "barriers": 2,
        "contract_category": "endsinout",
        "contract_category_display": "Ends Between/Ends Outside",
        "contract_display": "Ends Between",
        "contract_type": "EXPIRYRANGE",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "high_barrier": "7556.9932",
        "low_barrier": "7231.3151",
        "market": "synthetic_index",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "low_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "euro_non_atm",
        "barriers": 2,
        "contract_category": "endsinout",
        "contract_category_display": "Ends Between/Ends Outside",
        "contract_display": "Ends Outside",
        "contract_type": "EXPIRYMISS",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "high_barrier": "+6.0721",
        "low_barrier": -6.0601,
        "market": "synthetic_index",
        "max_contract_duration": "1d",
        "min_contract_duration": "2m",
        "sentiment": "high_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "euro_non_atm",
        "barriers": 2,
        "contract_category": "endsinout",
        "contract_category_display": "Ends Between/Ends Outside",
        "contract_display": "Ends Between",
        "contract_type": "EXPIRYRANGE",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "high_barrier": "+6.0721",
        "low_barrier": -6.0601,
        "market": "synthetic_index",
        "max_contract_duration": "1d",
        "min_contract_duration": "2m",
        "sentiment": "low_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "american",
        "barriers": 0,
        "contract_category": "highlowticks",
        "contract_category_display": "High/Low Ticks",
        "contract_display": "High Tick",
        "contract_type": "TICKHIGH",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "synthetic_index",
        "max_contract_duration": "5t",
        "min_contract_duration": "5t",
        "sentiment": "high",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "american",
        "barriers": 0,
        "contract_category": "highlowticks",
        "contract_category_display": "High/Low Ticks",
        "contract_display": "Low Tick",
        "contract_type": "TICKLOW",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "synthetic_index",
        "max_contract_duration": "5t",
        "min_contract_duration": "5t",
        "sentiment": "low",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "lookback",
        "barriers": 0,
        "contract_category": "lookback",
        "contract_category_display": "Lookbacks",
        "contract_display": "Close-Low",
        "contract_type": "LBFLOATCALL",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "synthetic_index",
        "max_contract_duration": "30m",
        "min_contract_duration": "1m",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "lookback",
        "barriers": 0,
        "contract_category": "lookback",
        "contract_category_display": "Lookbacks",
        "contract_display": "High-Close",
        "contract_type": "LBFLOATPUT",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "synthetic_index",
        "max_contract_duration": "30m",
        "min_contract_duration": "1m",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "lookback",
        "barriers": 0,
        "contract_category": "lookback",
        "contract_category_display": "Lookbacks",
        "contract_display": "High-Low",
        "contract_type": "LBHIGHLOW",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "synthetic_index",
        "max_contract_duration": "30m",
        "min_contract_duration": "1m",
        "sentiment": "updown",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier": "+2.4775",
        "barrier_category": "reset",
        "barriers": 1,
        "contract_category": "reset",
        "contract_category_display": "Reset Call/Reset Put",
        "contract_display": "Reset Call",
        "contract_type": "RESETCALL",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "synthetic_index",
        "max_contract_duration": "2h",
        "min_contract_duration": "20s",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier": "+2.4775",
        "barrier_category": "reset",
        "barriers": 1,
        "contract_category": "reset",
        "contract_category_display": "Reset Call/Reset Put",
        "contract_display": "Reset Put",
        "contract_type": "RESETPUT",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "synthetic_index",
        "max_contract_duration": "2h",
        "min_contract_duration": "20s",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier": "+1.2385",
        "barrier_category": "reset",
        "barriers": 1,
        "contract_category": "reset",
        "contract_category_display": "Reset Call/Reset Put",
        "contract_display": "Reset Call",
        "contract_type": "RESETCALL",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "synthetic_index",
        "max_contract_duration": "10t",
        "min_contract_duration": "5t",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier": "+1.2385",
        "barrier_category": "reset",
        "barriers": 1,
        "contract_category": "reset",
        "contract_category_display": "Reset Call/Reset Put",
        "contract_display": "Reset Put",
        "contract_type": "RESETPUT",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "synthetic_index",
        "max_contract_duration": "10t",
        "min_contract_duration": "5t",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier": "+0.7832",
        "barrier_category": "american",
        "barriers": 1,
        "contract_category": "runs",
        "contract_category_display": "Only Ups/Only Downs",
        "contract_display": "Only Ups",
        "contract_type": "RUNHIGH",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "synthetic_index",
        "max_contract_duration": "5t",
        "min_contract_duration": "2t",
        "sentiment": "up",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier": "+0.7832",
        "barrier_category": "american",
        "barriers": 1,
        "contract_category": "runs",
        "contract_category_display": "Only Ups/Only Downs",
        "contract_display": "Only Downs",
        "contract_type": "RUNLOW",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "synthetic_index",
        "max_contract_duration": "5t",
        "min_contract_duration": "2t",
        "sentiment": "down",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "american",
        "barriers": 2,
        "contract_category": "staysinout",
        "contract_category_display": "Stays Between/Goes Outside",
        "contract_display": "Stays Between",
        "contract_type": "RANGE",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "high_barrier": "7556.9932",
        "low_barrier": "7231.3151",
        "market": "synthetic_index",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "low_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "american",
        "barriers": 2,
        "contract_category": "staysinout",
        "contract_category_display": "Stays Between/Goes Outside",
        "contract_display": "Goes Outside",
        "contract_type": "UPORDOWN",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "high_barrier": "7556.9932",
        "low_barrier": "7231.3151",
        "market": "synthetic_index",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "high_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "american",
        "barriers": 2,
        "contract_category": "staysinout",
        "contract_category_display": "Stays Between/Goes Outside",
        "contract_display": "Stays Between",
        "contract_type": "RANGE",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "high_barrier": "+6.0721",
        "low_barrier": -6.0601,
        "market": "synthetic_index",
        "max_contract_duration": "1d",
        "min_contract_duration": "2m",
        "sentiment": "low_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier_category": "american",
        "barriers": 2,
        "contract_category": "staysinout",
        "contract_category_display": "Stays Between/Goes Outside",
        "contract_display": "Goes Outside",
        "contract_type": "UPORDOWN",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "high_barrier": "+6.0721",
        "low_barrier": -6.0601,
        "market": "synthetic_index",
        "max_contract_duration": "1d",
        "min_contract_duration": "2m",
        "sentiment": "high_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier": "7556.9932",
        "barrier_category": "american",
        "barriers": 1,
        "contract_category": "touchnotouch",
        "contract_category_display": "Touch/No Touch",
        "contract_display": "Touches",
        "contract_type": "ONETOUCH",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "market": "synthetic_index",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "high_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier": "7556.9932",
        "barrier_category": "american",
        "barriers": 1,
        "contract_category": "touchnotouch",
        "contract_category_display": "Touch/No Touch",
        "contract_display": "Does Not Touch",
        "contract_type": "NOTOUCH",
        "exchange_name": "RANDOM",
        "expiry_type": "daily",
        "market": "synthetic_index",
        "max_contract_duration": "365d",
        "min_contract_duration": "1d",
        "sentiment": "low_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier": "+6.0721",
        "barrier_category": "american",
        "barriers": 1,
        "contract_category": "touchnotouch",
        "contract_category_display": "Touch/No Touch",
        "contract_display": "Touches",
        "contract_type": "ONETOUCH",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "synthetic_index",
        "max_contract_duration": "1d",
        "min_contract_duration": "2m",
        "sentiment": "high_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier": "+6.0721",
        "barrier_category": "american",
        "barriers": 1,
        "contract_category": "touchnotouch",
        "contract_category_display": "Touch/No Touch",
        "contract_display": "Does Not Touch",
        "contract_type": "NOTOUCH",
        "exchange_name": "RANDOM",
        "expiry_type": "intraday",
        "market": "synthetic_index",
        "max_contract_duration": "1d",
        "min_contract_duration": "2m",
        "sentiment": "low_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier": "+1.2385",
        "barrier_category": "american",
        "barriers": 1,
        "contract_category": "touchnotouch",
        "contract_category_display": "Touch/No Touch",
        "contract_display": "Touches",
        "contract_type": "ONETOUCH",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "synthetic_index",
        "max_contract_duration": "10t",
        "min_contract_duration": "5t",
        "sentiment": "high_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      },
      {
        "barrier": "+1.2385",
        "barrier_category": "american",
        "barriers": 1,
        "contract_category": "touchnotouch",
        "contract_category_display": "Touch/No Touch",
        "contract_display": "Does Not Touch",
        "contract_type": "NOTOUCH",
        "exchange_name": "RANDOM",
        "expiry_type": "tick",
        "market": "synthetic_index",
        "max_contract_duration": "10t",
        "min_contract_duration": "5t",
        "sentiment": "low_vol",
        "start_type": "spot",
        "submarket": "random_index",
        "underlying_symbol": "R_50"
      }
    ],
    "close": 1588809599,
    "feed_license": "realtime",
    "hit_count": 55,
    "open": 1588723200,
    "spot": 7389.8297
  },
  "echo_req": {
    "contracts_for": "R_50",
    "currency": "USD",
    "landing_company": "svg",
    "product_type": "basic"
  },
  "msg_type": "contracts_for"
}
''';
