/// Autogenerated from flutter_deriv_api|lib/api/account_statistics_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'account_statistics_send.g.dart';

/// JSON conversion for 'account_statistics_send'
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class AccountStatisticsRequest extends Request {
  /// Initialize AccountStatisticsRequest
  AccountStatisticsRequest({
    this.accountStatistics = 1,
    Map<String, dynamic> passthrough,
    int reqId,
  }) : super(
          msgType: 'account_statistics',
          passthrough: passthrough,
          reqId: reqId,
        );

  /// Creates instance from JSON
  factory AccountStatisticsRequest.fromJson(Map<String, dynamic> json) =>
      _$AccountStatisticsRequestFromJson(json);

  // Properties
  /// Must be `1`
  int accountStatistics;

  /// Converts to JSON
  @override
  Map<String, dynamic> toJson() => _$AccountStatisticsRequestToJson(this);
}
