/// Autogenerated from flutter_deriv_api|lib/api/account_statistics_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'account_statistics_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class AccountStatisticsResponse extends Response {
  ///
  AccountStatisticsResponse(
      {this.accountStatistics,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Instance from JSON
  factory AccountStatisticsResponse.fromJson(Map<String, dynamic> json) =>
      _$AccountStatisticsResponseFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$AccountStatisticsResponseToJson(this);

  // Properties
  /// Response of account statistics
  Map<String, dynamic> accountStatistics;
}
