/// Autogenerated from flutter_deriv_api|lib/api/account_security_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'account_security_receive.g.dart';

/// JSON conversion for 'account_security_receive'
@JsonSerializable(nullable: true, fieldRename: FieldRename.snake)
class AccountSecurityResponse extends Response {
  /// Initialize AccountSecurityResponse
  AccountSecurityResponse(
      {this.accountSecurity,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Factory constructor to initialize from JSON
  factory AccountSecurityResponse.fromJson(Map<String, dynamic> json) =>
      _$AccountSecurityResponseFromJson(json);

  // Properties
  /// The information of 2-Factor authentication.
  Map<String, dynamic> accountSecurity;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$AccountSecurityResponseToJson(this);
}
