/// Autogenerated from flutter_deriv_api|lib/api/account_statistics_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'account_statistics_receive.g.dart';

/// JSON conversion for 'account_statistics_receive'
@JsonSerializable(nullable: true, fieldRename: FieldRename.snake)
class AccountStatisticsResponse extends Response {
  /// Initialize AccountStatisticsResponse
  AccountStatisticsResponse(
      {this.accountStatistics,
      Map<String, dynamic> echoReq,
      Map<String, dynamic> error,
      String msgType,
      int reqId})
      : super(echoReq: echoReq, error: error, msgType: msgType, reqId: reqId);

  /// Creates instance from JSON
  factory AccountStatisticsResponse.fromJson(Map<String, dynamic> json) =>
      _$AccountStatisticsResponseFromJson(json);

  // Properties
  /// Response of account statistics
  Map<String, dynamic> accountStatistics;

  /// Converts to JSON
  @override
  Map<String, dynamic> toJson() => _$AccountStatisticsResponseToJson(this);
}
