/// Autogenerated from flutter_deriv_api|lib/api/active_symbols_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'active_symbols_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ActiveSymbolsRequest {
  ActiveSymbolsRequest();
  factory ActiveSymbolsRequest.fromJson(Map<String, dynamic> json) =>
      _$ActiveSymbolsRequestFromJson(json);
  Map<String, dynamic> toJson() => _$ActiveSymbolsRequestToJson(this);

  // Properties
  String activeSymbols;

  /// If you use 'brief', only a subset of fields will be returned.
  String landingCompany;

  /// [Optional] If you specify this field, only symbols available for trading by that landing company will be returned. If you are logged in, only symbols available for trading by your landing company will be returned regardless of what you specify in this field.
  String productType;

  /// [Optional] If you specify this field, only symbols that can be traded through that product type will be returned.
  Map<String, dynamic> passthrough;

  /// [Optional] Used to pass data through the websocket, which may be retrieved via the echo_req output field.
  int reqId;

  /// [Optional] Used to map request to response.

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
