/// Autogenerated from flutter_deriv_api|lib/api/api_token_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'api_token_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ApiTokenRequest extends Request {
  ///
  ApiTokenRequest(
      {this.apiToken,
      this.deleteToken,
      this.newToken,
      this.newTokenScopes,
      Map<String, dynamic> passthrough,
      int reqId,
      this.validForCurrentIpOnly})
      : super(passthrough: passthrough, reqId: reqId);

  ///
  factory ApiTokenRequest.fromJson(Map<String, dynamic> json) =>
      _$ApiTokenRequestFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$ApiTokenRequestToJson(this);

  // Properties
  /// Must be `1`
  int apiToken;

  /// [Optional] The token to remove.
  String deleteToken;

  /// [Optional] The name of the created token.
  String newToken;

  /// [Optional] List of permission scopes to provide with the token.
  List<String> newTokenScopes;

  /// [Optional] If you set this parameter during token creation, then the token created will only work for the IP address that was used to create the token
  int validForCurrentIpOnly;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
