/// Autogenerated from flutter_deriv_api|lib/api/app_register_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'app_register_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class AppRegisterResponse extends Response {
  ///
  AppRegisterResponse(
      {this.appRegister,
      Map<String, dynamic> echoReq,
      String msgType,
      int reqId})
      : super(echoReq: echoReq, msgType: msgType, reqId: reqId);

  ///
  factory AppRegisterResponse.fromJson(Map<String, dynamic> json) =>
      _$AppRegisterResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$AppRegisterResponseToJson(this);

  // Properties
  /// The information of the created application.
  Map<String, dynamic> appRegister;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
