/// Autogenerated from flutter_deriv_api|lib/api/app_delete_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'app_delete_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class AppDeleteResponse extends Response {
  ///
  AppDeleteResponse(
      {this.appDelete,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Instance from JSON
  factory AppDeleteResponse.fromJson(Map<String, dynamic> json) =>
      _$AppDeleteResponseFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$AppDeleteResponseToJson(this);

  // Properties
  /// 1 on success
  int appDelete;
}
