/// Autogenerated from flutter_deriv_api|lib/api/app_list_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'app_list_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class AppListResponse extends Response {
  ///
  AppListResponse(
      {this.appList,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Instance from JSON
  factory AppListResponse.fromJson(Map<String, dynamic> json) =>
      _$AppListResponseFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$AppListResponseToJson(this);

  // Properties
  /// List of created applications for the authorized account.
  List<Map<String, dynamic>> appList;
}
