/// Autogenerated from flutter_deriv_api|lib/api/app_update_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'app_update_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class AppUpdateRequest {
  AppUpdateRequest();
  factory AppUpdateRequest.fromJson(Map<String, dynamic> json) =>
      _$AppUpdateRequestFromJson(json);
  Map<String, dynamic> toJson() => _$AppUpdateRequestToJson(this);

  // Properties
  /// Markup to be added to contract prices (as a percentage of contract payout). Min: 0, Max: 5
  num appMarkupPercentage;

  /// Application app_id
  int appUpdate;

  /// Application's App Store URL (if applicable)
  String appstore;

  /// Application's GitHub page (for open-source projects)
  String github;

  /// Application's Google Play URL (if applicable)
  String googleplay;

  /// Application's homepage
  String homepage;

  /// Application name
  String name;

  /// [Optional] Used to pass data through the websocket, which may be retrieved via the echo_req output field.
  Map<String, dynamic> passthrough;

  /// Application redirect_uri
  String redirectUri;

  /// [Optional] Used to map request to response.
  int reqId;

  /// Change scopes will revoke all user's grants and log them out.
  List<String> scopes;

  /// Application verification_uri
  String verificationUri;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
