/// Autogenerated from flutter_deriv_api|lib/api/app_markup_details_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'app_markup_details_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class AppMarkupDetailsResponse extends Response {
  ///
  AppMarkupDetailsResponse(
      {this.appMarkupDetails,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  ///
  factory AppMarkupDetailsResponse.fromJson(Map<String, dynamic> json) =>
      _$AppMarkupDetailsResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$AppMarkupDetailsResponseToJson(this);

  // Properties
  /// App Markup transaction details
  Map<String, dynamic> appMarkupDetails;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
