/// Autogenerated from flutter_deriv_api|lib/api/app_register_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'app_register_receive.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class AppRegisterResponse {
  AppRegisterResponse(
      {this.appRegister, this.echoReq, this.msgType, this.reqId});
  factory AppRegisterResponse.fromJson(Map<String, dynamic> json) =>
      _$AppRegisterResponseFromJson(json);
  Map<String, dynamic> toJson() => _$AppRegisterResponseToJson(this);

  // Properties
  /// The information of the created application.
  Map<String, dynamic> appRegister;

  /// Echo of the request made.
  Map<String, dynamic> echoReq;

  /// Action name of the request made.
  String msgType;

  /// Optional field sent in request to map to response, present only when request contains `req_id`.
  int reqId;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
