/// Autogenerated from flutter_deriv_api|lib/api/app_markup_details_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'app_markup_details_receive.g.dart';

/// JSON conversion for 'app_markup_details_receive'
@JsonSerializable(nullable: true, fieldRename: FieldRename.snake)
class AppMarkupDetailsResponse extends Response {
  /// Initialize AppMarkupDetailsResponse
  AppMarkupDetailsResponse(
      {this.appMarkupDetails,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Factory constructor to initialize from JSON
  factory AppMarkupDetailsResponse.fromJson(Map<String, dynamic> json) =>
      _$AppMarkupDetailsResponseFromJson(json);

  // Properties
  /// App Markup transaction details
  Map<String, dynamic> appMarkupDetails;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$AppMarkupDetailsResponseToJson(this);
}
