/// Autogenerated from flutter_deriv_api|lib/api/app_update_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'app_update_receive.g.dart';

/// JSON conversion for 'app_update_receive'
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class AppUpdateResponse extends Response {
  /// Initialize AppUpdateResponse
  AppUpdateResponse(
      {this.appUpdate,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Factory constructor to initialize from JSON
  factory AppUpdateResponse.fromJson(Map<String, dynamic> json) =>
      _$AppUpdateResponseFromJson(json);

  // Properties
  /// Information of the updated application.
  Map<String, dynamic> appUpdate;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$AppUpdateResponseToJson(this);
}
