/// Autogenerated from flutter_deriv_api|lib/api/app_register_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'app_register_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class AppRegisterRequest {
  AppRegisterRequest();
  factory AppRegisterRequest.fromJson(Map<String, dynamic> json) =>
      _$AppRegisterRequestFromJson(json);
  Map<String, dynamic> toJson() => _$AppRegisterRequestToJson(this);

  // Properties
  /// Markup to be added to contract prices (as a percentage of contract payout). Min: 0, Max: 5
  num appMarkupPercentage;

  /// Must be 1
  int appRegister;

  /// Application's App Store URL (if applicable)
  String appstore;

  /// Application's GitHub page (for open-source projects)
  String github;

  /// Application's Google Play URL (if applicable)
  String googleplay;

  /// Application's homepage
  String homepage;

  /// Application name
  String name;

  /// [Optional] Used to pass data through the websocket, which may be retrieved via the echo_req output field.
  Map<String, dynamic> passthrough;

  /// Application redirect_uri
  String redirectUri;

  /// [Optional] Used to map request to response.
  int reqId;

  /// List of permission scopes to grant the application.
  List<String> scopes;

  /// Application verification_uri
  String verificationUri;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
