/// Autogenerated from flutter_deriv_api|lib/api/asset_index_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'asset_index_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class AssetIndexRequest extends Request {
  ///
  AssetIndexRequest(
      {this.assetIndex,
      this.landingCompany,
      int reqId,
      Map<String, dynamic> passthrough})
      : super(reqId: reqId, passthrough: passthrough);

  /// Instance from JSON
  factory AssetIndexRequest.fromJson(Map<String, dynamic> json) =>
      _$AssetIndexRequestFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$AssetIndexRequestToJson(this);

  // Properties
  /// Must be `1`
  int assetIndex;

  /// [Optional] If specified, will return only the underlyings for the specified landing company.
  String landingCompany;
}
