/// Autogenerated from flutter_deriv_api|lib/api/asset_index_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'asset_index_receive.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class AssetIndexResponse {
  AssetIndexResponse();
  factory AssetIndexResponse.fromJson(Map<String, dynamic> json) =>
      _$AssetIndexResponseFromJson(json);
  Map<String, dynamic> toJson() => _$AssetIndexResponseToJson(this);

  // Properties
  List<String> assetIndex;

  /// List of underlyings by their display name and symbol followed by their available contract types and duration boundaries.
  Map<String, dynamic> echoReq;

  /// Echo of the request made.
  String msgType;

  /// Action name of the request made.
  int reqId;

  /// Optional field sent in request to map to response, present only when request contains req_id.

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
