/// Autogenerated from flutter_deriv_api|lib/api/balance_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'balance_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class BalanceRequest {
  BalanceRequest();
  factory BalanceRequest.fromJson(Map<String, dynamic> json) =>
      _$BalanceRequestFromJson(json);
  Map<String, dynamic> toJson() => _$BalanceRequestToJson(this);

  // Properties
  int balance;

  /// Must be 1
  String account;

  /// [Optional] If set to 'all', return the balances of all accounts one by one; if set to 'current', return the balance of current account; if set as an account id,  return the balance of that account. Default is current
  int subscribe;

  /// If set to 1, will send updates whenever the balance changes.
  Map<String, dynamic> passthrough;

  /// [Optional] Used to pass data through the websocket, which may be retrieved via the echo_req output field.
  int reqId;

  /// [Optional] Used to map request to response.

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
