/// Autogenerated from flutter_deriv_api|lib/api/buy_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'buy_receive.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class BuyResponse {
  BuyResponse();
  factory BuyResponse.fromJson(Map<String, dynamic> json) =>
      _$BuyResponseFromJson(json);
  Map<String, dynamic> toJson() => _$BuyResponseToJson(this);

  // Properties
  /// Receipt confirmation for the purchase
  Map<String, dynamic> buy;

  /// Echo of the request made.
  Map<String, dynamic> echoReq;

  /// Action name of the request made.
  String msgType;

  /// Optional field sent in request to map to response, present only when request contains req_id.
  int reqId;

  /// For subscription requests only
  Map<String, dynamic> subscription;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
