/// Autogenerated from flutter_deriv_api|lib/api/cashier_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'cashier_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class CashierResponse extends Response {
  ///
  CashierResponse(
      {this.cashier,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Instance from JSON
  factory CashierResponse.fromJson(Map<String, dynamic> json) =>
      _$CashierResponseFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$CashierResponseToJson(this);

  // Properties
  /// Cashier URL. Note: possible error codes are: ASK_TNC_APPROVAL (API tnc_approval), ASK_AUTHENTICATE, ASK_UK_FUNDS_PROTECTION (API tnc_approval), ASK_CURRENCY (API set_account_currency), ASK_EMAIL_VERIFY (verify_email), ASK_FIX_DETAILS (API set_settings).
  String cashier;
}
