/// Autogenerated from flutter_deriv_api|lib/api/change_password_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'change_password_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ChangePasswordResponse extends Response {
  ///
  ChangePasswordResponse(
      {this.changePassword,
      Map<String, dynamic> echoReq,
      String msgType,
      int reqId})
      : super(echoReq: echoReq, msgType: msgType, reqId: reqId);

  ///
  factory ChangePasswordResponse.fromJson(Map<String, dynamic> json) =>
      _$ChangePasswordResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$ChangePasswordResponseToJson(this);

  // Properties
  /// If set to 1, password updated.
  int changePassword;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
