/// Autogenerated from flutter_deriv_api|lib/api/contract_update_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'contract_update_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ContractUpdateResponse extends Response {
  ///
  ContractUpdateResponse(
      {this.contractUpdate,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Instance from JSON
  factory ContractUpdateResponse.fromJson(Map<String, dynamic> json) =>
      _$ContractUpdateResponseFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$ContractUpdateResponseToJson(this);

  // Properties
  /// Contains the update status of the request
  Map<String, dynamic> contractUpdate;
}
