/// Autogenerated from flutter_deriv_api|lib/api/contracts_for_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'contracts_for_receive.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ContractsForResponse {
  ContractsForResponse();
  factory ContractsForResponse.fromJson(Map<String, dynamic> json) =>
      _$ContractsForResponseFromJson(json);
  Map<String, dynamic> toJson() => _$ContractsForResponseToJson(this);

  // Properties
  /// List of available contracts. Note: if the user is authenticated, then only contracts allowed under his account will be returned.
  Map<String, dynamic> contractsFor;

  /// Echo of the request made.
  Map<String, dynamic> echoReq;

  /// Action name of the request made.
  String msgType;

  /// Optional field sent in request to map to response, present only when request contains req_id.
  int reqId;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
