/// Autogenerated from flutter_deriv_api|lib/api/contract_update_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'contract_update_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ContractUpdateRequest extends Request {
  ///
  ContractUpdateRequest(
      {this.contractId,
      this.contractUpdate,
      this.limitOrder,
      int reqId,
      Map<String, dynamic> passthrough})
      : super(reqId: reqId, passthrough: passthrough);

  ///
  factory ContractUpdateRequest.fromJson(Map<String, dynamic> json) =>
      _$ContractUpdateRequestFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$ContractUpdateRequestToJson(this);

  // Properties
  /// Internal unique contract identifier.
  int contractId;

  /// Must be `1`
  int contractUpdate;

  /// Specify limit order to update.
  Map<String, dynamic> limitOrder;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
