/// Autogenerated from flutter_deriv_api|lib/api/contracts_for_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'contracts_for_send.g.dart';

/// JSON conversion for 'contracts_for_send'
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ContractsForRequest extends Request {
  /// Initialize ContractsForRequest
  ContractsForRequest(
      {this.contractsFor,
      this.currency,
      this.landingCompany,
      this.productType,
      int reqId,
      Map<String, dynamic> passthrough})
      : super(reqId: reqId, passthrough: passthrough);

  /// Factory constructor to initialize from JSON
  factory ContractsForRequest.fromJson(Map<String, dynamic> json) =>
      _$ContractsForRequestFromJson(json);

  // Properties
  /// The short symbol name (obtained from active_symbols call).
  String contractsFor;

  /// [Optional] Currency of the contract's stake and payout (obtained from payout_currencies call).
  String currency;

  /// [Optional] Indicates which landing_company to get a list of contracts for. If you are logged in, your landing company will override this field.
  String landingCompany;

  /// [Optional] If you specify this field, only contracts tradable through that contract type will be returned.
  String productType;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$ContractsForRequestToJson(this);
}
