/// Autogenerated from flutter_deriv_api|lib/api/copy_stop_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'copy_stop_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class CopyStopResponse extends Response {
  ///
  CopyStopResponse(
      {this.copyStop,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  ///
  factory CopyStopResponse.fromJson(Map<String, dynamic> json) =>
      _$CopyStopResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$CopyStopResponseToJson(this);

  // Properties
  /// Copy stopping confirmation. Returns 1 is success.
  int copyStop;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
