/// Autogenerated from flutter_deriv_api|lib/api/copytrading_statistics_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'copytrading_statistics_receive.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class CopytradingStatisticsResponse {
  CopytradingStatisticsResponse();
  factory CopytradingStatisticsResponse.fromJson(Map<String, dynamic> json) =>
      _$CopytradingStatisticsResponseFromJson(json);
  Map<String, dynamic> toJson() => _$CopytradingStatisticsResponseToJson(this);

  // Properties
  Map<String, dynamic> copytradingStatistics;

  /// Statistics of the trader
  Map<String, dynamic> echoReq;

  /// Echo of the request made.
  String msgType;

  /// Action name of the request made.
  int reqId;

  /// Optional field sent in request to map to response, present only when request contains req_id.

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
