/// Autogenerated from flutter_deriv_api|lib/api/copytrading_statistics_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'copytrading_statistics_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class CopytradingStatisticsRequest {
  CopytradingStatisticsRequest();
  factory CopytradingStatisticsRequest.fromJson(Map<String, dynamic> json) =>
      _$CopytradingStatisticsRequestFromJson(json);
  Map<String, dynamic> toJson() => _$CopytradingStatisticsRequestToJson(this);

  // Properties
  int copytradingStatistics;

  /// Must be 1
  String traderId;

  /// The ID of the target trader.
  Map<String, dynamic> passthrough;

  /// [Optional] Used to pass data through the websocket, which may be retrieved via the echo_req output field.
  int reqId;

  /// [Optional] Used to map request to response.

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
