/// Autogenerated from flutter_deriv_api|lib/api/copytrading_statistics_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'copytrading_statistics_receive.g.dart';

/// JSON conversion for 'copytrading_statistics_receive'
@JsonSerializable(nullable: true, fieldRename: FieldRename.snake)
class CopytradingStatisticsResponse extends Response {
  /// Initialize CopytradingStatisticsResponse
  CopytradingStatisticsResponse(
      {this.copytradingStatistics,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Factory constructor to initialize from JSON
  factory CopytradingStatisticsResponse.fromJson(Map<String, dynamic> json) =>
      _$CopytradingStatisticsResponseFromJson(json);

  // Properties
  /// Statistics of the trader
  Map<String, dynamic> copytradingStatistics;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$CopytradingStatisticsResponseToJson(this);
}
