/// Autogenerated from flutter_deriv_api|lib/api/copy_start_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'copy_start_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class CopyStartResponse extends Response {
  ///
  CopyStartResponse(
      {this.copyStart,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Instance from JSON
  factory CopyStartResponse.fromJson(Map<String, dynamic> json) =>
      _$CopyStartResponseFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$CopyStartResponseToJson(this);

  // Properties
  /// Copy start confirmation. Returns 1 is success.
  int copyStart;
}
