/// Autogenerated from flutter_deriv_api|lib/api/copytrading_statistics_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'copytrading_statistics_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class CopytradingStatisticsRequest extends Request {
  ///
  CopytradingStatisticsRequest(
      {this.copytradingStatistics,
      this.traderId,
      int reqId,
      Map<String, dynamic> passthrough})
      : super(reqId: reqId, passthrough: passthrough);

  ///
  factory CopytradingStatisticsRequest.fromJson(Map<String, dynamic> json) =>
      _$CopytradingStatisticsRequestFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$CopytradingStatisticsRequestToJson(this);

  // Properties
  /// Must be `1`
  int copytradingStatistics;

  /// The ID of the target trader.
  String traderId;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
