/// Autogenerated from flutter_deriv_api|lib/api/document_upload_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'document_upload_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class DocumentUploadRequest {
  DocumentUploadRequest();
  factory DocumentUploadRequest.fromJson(Map<String, dynamic> json) =>
      _$DocumentUploadRequestFromJson(json);
  Map<String, dynamic> toJson() => _$DocumentUploadRequestToJson(this);

  // Properties
  int documentUpload;

  /// Must be 1
  String documentFormat;

  /// Document file format
  String documentId;

  /// [Optional] Document ID (required for Passport, Proof of ID and Driver's License)
  String documentType;

  /// Document type
  String expectedChecksum;

  /// The checksum of the file to be uploaded
  String expirationDate;

  /// [Optional] Document expiration date (required for Passport, Proof of ID and Driver's License)
  int fileSize;

  /// Document size (should be less than 3MB)
  String pageType;

  /// Optional field to determine document side
  Map<String, dynamic> passthrough;

  /// [Optional] Used to pass data through the websocket, which may be retrieved via the echo_req output field.
  int reqId;

  /// [Optional] Used to map request to response.

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
