/// Autogenerated from flutter_deriv_api|lib/api/document_upload_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'document_upload_receive.g.dart';

/// JSON conversion for 'document_upload_receive'
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class DocumentUploadResponse extends Response {
  /// Initialize DocumentUploadResponse
  DocumentUploadResponse(
      {this.documentUpload,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Factory constructor to initialize from JSON
  factory DocumentUploadResponse.fromJson(Map<String, dynamic> json) =>
      _$DocumentUploadResponseFromJson(json);

  // Properties
  /// Details of the uploaded documents.
  Map<String, dynamic> documentUpload;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$DocumentUploadResponseToJson(this);
}
