/// Autogenerated from flutter_deriv_api|lib/api/document_upload_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'document_upload_receive.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class DocumentUploadResponse {
  DocumentUploadResponse();
  factory DocumentUploadResponse.fromJson(Map<String, dynamic> json) =>
      _$DocumentUploadResponseFromJson(json);
  Map<String, dynamic> toJson() => _$DocumentUploadResponseToJson(this);

  // Properties
  /// Details of the uploaded documents.
  Map<String, dynamic> documentUpload;

  /// Echo of the request made.
  Map<String, dynamic> echoReq;

  /// Action name of the request made.
  String msgType;

  /// Optional field sent in request to map to response, present only when request contains req_id.
  int reqId;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
