/// Autogenerated from flutter_deriv_api|lib/api/exchange_rates_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'exchange_rates_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ExchangeRatesResponse extends Response {
  ///
  ExchangeRatesResponse(
      {this.exchangeRates,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  ///
  factory ExchangeRatesResponse.fromJson(Map<String, dynamic> json) =>
      _$ExchangeRatesResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$ExchangeRatesResponseToJson(this);

  // Properties

  /// Exchange rate values from base to all other currencies
  Map<String, dynamic> exchangeRates;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
