/// Autogenerated from flutter_deriv_api|lib/api/exchange_rates_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'exchange_rates_receive.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ExchangeRatesResponse {
  ExchangeRatesResponse(
      {this.echoReq, this.exchangeRates, this.msgType, this.reqId});
  factory ExchangeRatesResponse.fromJson(Map<String, dynamic> json) =>
      _$ExchangeRatesResponseFromJson(json);
  Map<String, dynamic> toJson() => _$ExchangeRatesResponseToJson(this);

  // Properties
  /// Echo of the request made.
  Map<String, dynamic> echoReq;

  /// Exchange rate values from base to all other currencies
  Map<String, dynamic> exchangeRates;

  /// Action name of the request made.
  String msgType;

  /// Optional field sent in request to map to response, present only when request contains `req_id`.
  int reqId;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
