/// Autogenerated from flutter_deriv_api|lib/api/forget_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'forget_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ForgetRequest extends Request {
  ///
  ForgetRequest({this.forget, int reqId, Map<String, dynamic> passthrough})
      : super(reqId: reqId, passthrough: passthrough);

  /// Instance from JSON
  factory ForgetRequest.fromJson(Map<String, dynamic> json) =>
      _$ForgetRequestFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$ForgetRequestToJson(this);

  // Properties
  /// ID of the real-time stream of messages to cancel.
  String forget;
}
