/// Autogenerated from flutter_deriv_api|lib/api/forget_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'forget_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ForgetResponse extends Response {
  ///
  ForgetResponse({this.echoReq, this.forget, this.msgType, this.reqId});

  ///
  factory ForgetResponse.fromJson(Map<String, dynamic> json) =>
      _$ForgetResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$ForgetResponseToJson(this);

  // Properties
  /// Echo of the request made.
  Map<String, dynamic> echoReq;

  /// If set to 1, stream exited and stopped. If set to 0, stream did not exist.
  int forget;

  /// Action name of the request made.
  String msgType;

  /// Optional field sent in request to map to response, present only when request contains `req_id`.
  int reqId;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
