/// Autogenerated from flutter_deriv_api|lib/api/forget_all_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'forget_all_receive.g.dart';

/// JSON conversion for 'forget_all_receive'
@JsonSerializable(nullable: true, fieldRename: FieldRename.snake)
class ForgetAllResponse extends Response {
  /// Initialize ForgetAllResponse
  ForgetAllResponse(
      {this.forgetAll,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Factory constructor to initialize from JSON
  factory ForgetAllResponse.fromJson(Map<String, dynamic> json) =>
      _$ForgetAllResponseFromJson(json);

  // Properties
  /// IDs of the cancelled streams
  List<String> forgetAll;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$ForgetAllResponseToJson(this);
}
