/// Autogenerated from flutter_deriv_api|lib/api/forget_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'forget_receive.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ForgetResponse {
  ForgetResponse();
  factory ForgetResponse.fromJson(Map<String, dynamic> json) =>
      _$ForgetResponseFromJson(json);
  Map<String, dynamic> toJson() => _$ForgetResponseToJson(this);

  // Properties
  int forget;

  /// If set to 1, stream exited and stopped. If set to 0, stream did not exist.
  Map<String, dynamic> echoReq;

  /// Echo of the request made.
  String msgType;

  /// Action name of the request made.
  int reqId;

  /// Optional field sent in request to map to response, present only when request contains req_id.

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
