/// Autogenerated from flutter_deriv_api|lib/api/forget_all_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'forget_all_send.g.dart';

/// JSON conversion for 'forget_all_send'
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ForgetAllRequest extends Request {
  /// Initialize ForgetAllRequest
  ForgetAllRequest(
      {this.forgetAll, Map<String, dynamic> passthrough, int reqId})
      : super(passthrough: passthrough, reqId: reqId);

  /// Creates instance from JSON
  factory ForgetAllRequest.fromJson(Map<String, dynamic> json) =>
      _$ForgetAllRequestFromJson(json);

  // Properties
  /// Cancel all streams by type. The value can be either a single type e.g. `"ticks"`, or an array of multiple types e.g. `["candles", "ticks"]`.
  String forgetAll;

  /// Converts to JSON
  @override
  Map<String, dynamic> toJson() => _$ForgetAllRequestToJson(this);
}
