/// Autogenerated from flutter_deriv_api|lib/api/get_financial_assessment_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'get_financial_assessment_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class GetFinancialAssessmentResponse extends Response {
  ///
  GetFinancialAssessmentResponse(
      {this.getFinancialAssessment,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Instance from JSON
  factory GetFinancialAssessmentResponse.fromJson(Map<String, dynamic> json) =>
      _$GetFinancialAssessmentResponseFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$GetFinancialAssessmentResponseToJson(this);

  // Properties
  /// Client's financial assessment details
  Map<String, dynamic> getFinancialAssessment;
}
