/// Autogenerated from flutter_deriv_api|lib/api/get_account_status_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'get_account_status_receive.g.dart';

/// JSON conversion for 'get_account_status_receive'
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class GetAccountStatusResponse extends Response {
  /// Initialize GetAccountStatusResponse
  GetAccountStatusResponse(
      {this.getAccountStatus,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Factory constructor to initialize from JSON
  factory GetAccountStatusResponse.fromJson(Map<String, dynamic> json) =>
      _$GetAccountStatusResponseFromJson(json);

  // Properties
  /// Account status details
  Map<String, dynamic> getAccountStatus;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$GetAccountStatusResponseToJson(this);
}
