/// Autogenerated from flutter_deriv_api|lib/api/get_financial_assessment_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'get_financial_assessment_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class GetFinancialAssessmentResponse extends Response {
  ///
  GetFinancialAssessmentResponse(
      {Map<String, dynamic> echoReq,
      this.getFinancialAssessment,
      String msgType,
      int reqId})
      : super(echoReq: echoReq, msgType: msgType, reqId: reqId);

  ///
  factory GetFinancialAssessmentResponse.fromJson(Map<String, dynamic> json) =>
      _$GetFinancialAssessmentResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$GetFinancialAssessmentResponseToJson(this);

  // Properties

  /// Client's financial assessment details
  Map<String, dynamic> getFinancialAssessment;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
