/// Autogenerated from flutter_deriv_api|lib/api/get_settings_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'get_settings_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class GetSettingsResponse extends Response {
  ///
  GetSettingsResponse(
      {this.getSettings,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  ///
  factory GetSettingsResponse.fromJson(Map<String, dynamic> json) =>
      _$GetSettingsResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$GetSettingsResponseToJson(this);

  // Properties

  /// User information and settings.
  Map<String, dynamic> getSettings;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
