/// Autogenerated from flutter_deriv_api|lib/api/get_limits_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'get_limits_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class GetLimitsRequest extends Request {
  ///
  GetLimitsRequest(
      {this.getLimits, Map<String, dynamic> passthrough, int reqId})
      : super(passthrough: passthrough, reqId: reqId);

  ///
  factory GetLimitsRequest.fromJson(Map<String, dynamic> json) =>
      _$GetLimitsRequestFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$GetLimitsRequestToJson(this);

  // Properties
  /// Must be `1`
  int getLimits;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
