/// Autogenerated from flutter_deriv_api|lib/api/get_limits_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'get_limits_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class GetLimitsResponse extends Response {
  ///
  GetLimitsResponse(
      {this.getLimits,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Instance from JSON
  factory GetLimitsResponse.fromJson(Map<String, dynamic> json) =>
      _$GetLimitsResponseFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$GetLimitsResponseToJson(this);

  // Properties
  /// Trading limits of real account user
  Map<String, dynamic> getLimits;
}
