/// Autogenerated from flutter_deriv_api|lib/api/get_financial_assessment_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'get_financial_assessment_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class GetFinancialAssessmentRequest {
  GetFinancialAssessmentRequest(
      {this.getFinancialAssessment, this.passthrough, this.reqId});
  factory GetFinancialAssessmentRequest.fromJson(Map<String, dynamic> json) =>
      _$GetFinancialAssessmentRequestFromJson(json);
  Map<String, dynamic> toJson() => _$GetFinancialAssessmentRequestToJson(this);

  // Properties
  /// Must be `1`
  int getFinancialAssessment;

  /// [Optional] Used to pass data through the websocket, which may be retrieved via the `echo_req` output field.
  Map<String, dynamic> passthrough;

  /// [Optional] Used to map request to response.
  int reqId;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
