/// Autogenerated from flutter_deriv_api|lib/api/landing_company_details_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'landing_company_details_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class LandingCompanyDetailsRequest extends Request {
  ///
  LandingCompanyDetailsRequest(
      {this.landingCompanyDetails, int reqId, Map<String, dynamic> passthrough})
      : super(reqId: reqId, passthrough: passthrough);

  /// Instance from JSON
  factory LandingCompanyDetailsRequest.fromJson(Map<String, dynamic> json) =>
      _$LandingCompanyDetailsRequestFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$LandingCompanyDetailsRequestToJson(this);

  // Properties
  /// Landing company shortcode.
  String landingCompanyDetails;
}
