/// Autogenerated from flutter_deriv_api|lib/api/landing_company_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'landing_company_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class LandingCompanyRequest {
  LandingCompanyRequest();
  factory LandingCompanyRequest.fromJson(Map<String, dynamic> json) =>
      _$LandingCompanyRequestFromJson(json);
  Map<String, dynamic> toJson() => _$LandingCompanyRequestToJson(this);

  // Properties
  String landingCompany;

  /// Client's 2-letter country code (obtained from residence_list call).
  Map<String, dynamic> passthrough;

  /// [Optional] Used to pass data through the websocket, which may be retrieved via the echo_req output field.
  int reqId;

  /// [Optional] Used to map request to response.

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
