/// Autogenerated from flutter_deriv_api|lib/api/landing_company_details_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'landing_company_details_receive.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class LandingCompanyDetailsResponse {
  LandingCompanyDetailsResponse();
  factory LandingCompanyDetailsResponse.fromJson(Map<String, dynamic> json) =>
      _$LandingCompanyDetailsResponseFromJson(json);
  Map<String, dynamic> toJson() => _$LandingCompanyDetailsResponseToJson(this);

  // Properties
  Map<String, dynamic> landingCompanyDetails;

  /// The detailed information of the requested landing company.
  Map<String, dynamic> echoReq;

  /// Echo of the request made.
  String msgType;

  /// Action name of the request made.
  int reqId;

  /// Optional field sent in request to map to response, present only when request contains req_id.

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
