/// Autogenerated from flutter_deriv_api|lib/api/logout_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'logout_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class LogoutResponse extends Response {
  ///
  LogoutResponse(
      {this.logout,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  ///
  factory LogoutResponse.fromJson(Map<String, dynamic> json) =>
      _$LogoutResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$LogoutResponseToJson(this);

  // Properties

  /// The result of logout request which is 1
  int logout;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
