/// Autogenerated from flutter_deriv_api|lib/api/mt5_new_account_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'mt5_new_account_receive.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class Mt5NewAccountResponse {
  Mt5NewAccountResponse();
  factory Mt5NewAccountResponse.fromJson(Map<String, dynamic> json) =>
      _$Mt5NewAccountResponseFromJson(json);
  Map<String, dynamic> toJson() => _$Mt5NewAccountResponseToJson(this);

  // Properties
  Map<String, dynamic> mt5NewAccount;

  /// New MT5 account details
  Map<String, dynamic> echoReq;

  /// Echo of the request made.
  String msgType;

  /// Action name of the request made.
  int reqId;

  /// Optional field sent in request to map to response, present only when request contains req_id.

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
