/// Autogenerated from flutter_deriv_api|lib/api/mt5_password_change_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'mt5_password_change_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class Mt5PasswordChangeRequest {
  Mt5PasswordChangeRequest(
      {this.login,
      this.mt5PasswordChange,
      this.newPassword,
      this.oldPassword,
      this.passthrough,
      this.passwordType,
      this.reqId});
  factory Mt5PasswordChangeRequest.fromJson(Map<String, dynamic> json) =>
      _$Mt5PasswordChangeRequestFromJson(json);
  Map<String, dynamic> toJson() => _$Mt5PasswordChangeRequestToJson(this);

  // Properties
  /// MT5 user login
  String login;

  /// Must be `1`
  int mt5PasswordChange;

  /// New password of the account. For validation (length within 8-25 chars, accepts at least 2 out of the following 3 types of characters: uppercase letters, lowercase letters, and numbers).
  String newPassword;

  /// Old password for validation (non-empty string, accepts any printable ASCII character)
  String oldPassword;

  /// [Optional] Used to pass data through the websocket, which may be retrieved via the `echo_req` output field.
  Map<String, dynamic> passthrough;

  /// [Optional] Type of the password to change.
  String passwordType;

  /// [Optional] Used to map request to response.
  int reqId;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
