/// Autogenerated from flutter_deriv_api|lib/api/mt5_password_reset_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'mt5_password_reset_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class Mt5PasswordResetRequest {
  Mt5PasswordResetRequest();
  factory Mt5PasswordResetRequest.fromJson(Map<String, dynamic> json) =>
      _$Mt5PasswordResetRequestFromJson(json);
  Map<String, dynamic> toJson() => _$Mt5PasswordResetRequestToJson(this);

  // Properties
  int mt5PasswordReset;

  /// Must be 1
  String login;

  /// MT5 user login
  String newPassword;

  /// New password of the account (length within 8-25 chars, accepts any printable ASCII character).
  String passwordType;

  /// Password type main/investor (default: main)
  String verificationCode;

  /// Email verification code (received from a verify_email call, which must be done first)
  Map<String, dynamic> passthrough;

  /// [Optional] Used to pass data through the websocket, which may be retrieved via the echo_req output field.
  int reqId;

  /// [Optional] Used to map request to response.

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
