/// Autogenerated from flutter_deriv_api|lib/api/mt5_login_list_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'mt5_login_list_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class Mt5LoginListResponse extends Response {
  ///
  Mt5LoginListResponse(
      {Map<String, dynamic> echoReq,
      String msgType,
      this.mt5LoginList,
      int reqId})
      : super(echoReq: echoReq, msgType: msgType, reqId: reqId);

  ///
  factory Mt5LoginListResponse.fromJson(Map<String, dynamic> json) =>
      _$Mt5LoginListResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$Mt5LoginListResponseToJson(this);

  // Properties

  /// Array containing MT5 account objects.
  List<Map<String, dynamic>> mt5LoginList;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
