/// Autogenerated from flutter_deriv_api|lib/api/mt5_get_settings_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'mt5_get_settings_send.g.dart';

/// JSON conversion for 'mt5_get_settings_send'
@JsonSerializable(nullable: true, fieldRename: FieldRename.snake)
class Mt5GetSettingsRequest extends Request {
  /// Initialize Mt5GetSettingsRequest
  Mt5GetSettingsRequest(
      {this.login,
      this.mt5GetSettings = 1,
      Map<String, dynamic> passthrough,
      int reqId})
      : super(passthrough: passthrough, reqId: reqId);

  /// Creates instance from JSON
  factory Mt5GetSettingsRequest.fromJson(Map<String, dynamic> json) =>
      _$Mt5GetSettingsRequestFromJson(json);

  // Properties
  /// MT5 user login
  String login;

  /// Must be `1`
  int mt5GetSettings;

  /// Converts to JSON
  @override
  Map<String, dynamic> toJson() => _$Mt5GetSettingsRequestToJson(this);
}
