/// Autogenerated from flutter_deriv_api|lib/api/mt5_password_reset_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'mt5_password_reset_receive.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class Mt5PasswordResetResponse {
  Mt5PasswordResetResponse();
  factory Mt5PasswordResetResponse.fromJson(Map<String, dynamic> json) =>
      _$Mt5PasswordResetResponseFromJson(json);
  Map<String, dynamic> toJson() => _$Mt5PasswordResetResponseToJson(this);

  // Properties
  /// Echo of the request made.
  Map<String, dynamic> echoReq;

  /// Action name of the request made.
  String msgType;

  /// 1 on success
  int mt5PasswordReset;

  /// Optional field sent in request to map to response, present only when request contains req_id.
  int reqId;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
