/// Autogenerated from flutter_deriv_api|lib/api/mt5_withdrawal_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'mt5_withdrawal_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class Mt5WithdrawalRequest {
  Mt5WithdrawalRequest();
  factory Mt5WithdrawalRequest.fromJson(Map<String, dynamic> json) =>
      _$Mt5WithdrawalRequestFromJson(json);
  Map<String, dynamic> toJson() => _$Mt5WithdrawalRequestToJson(this);

  // Properties
  int mt5Withdrawal;

  /// Must be 1
  num amount;

  /// Amount to withdraw (in the currency of the MT5 account); min = $1 or an equivalent amount, max = $20000 or an equivalent amount.
  String fromMt5;

  /// MT5 account login to withdraw money from
  String toBinary;

  /// Binary account loginid to transfer money to
  Map<String, dynamic> passthrough;

  /// [Optional] Used to pass data through the websocket, which may be retrieved via the echo_req output field.
  int reqId;

  /// [Optional] Used to map request to response.

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
