/// Autogenerated from flutter_deriv_api|lib/api/mt5_password_change_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'mt5_password_change_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class Mt5PasswordChangeResponse extends Response {
  ///
  Mt5PasswordChangeResponse(
      {this.mt5PasswordChange,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Instance from JSON
  factory Mt5PasswordChangeResponse.fromJson(Map<String, dynamic> json) =>
      _$Mt5PasswordChangeResponseFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$Mt5PasswordChangeResponseToJson(this);

  // Properties
  /// `1` on success
  int mt5PasswordChange;
}
