/// Autogenerated from flutter_deriv_api|lib/api/mt5_deposit_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'mt5_deposit_receive.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class Mt5DepositResponse {
  Mt5DepositResponse();
  factory Mt5DepositResponse.fromJson(Map<String, dynamic> json) =>
      _$Mt5DepositResponseFromJson(json);
  Map<String, dynamic> toJson() => _$Mt5DepositResponseToJson(this);

  // Properties
  /// Withdrawal reference ID of Binary account
  int binaryTransactionId;

  /// Echo of the request made.
  Map<String, dynamic> echoReq;

  /// Action name of the request made.
  String msgType;

  /// 1 on success
  int mt5Deposit;

  /// Optional field sent in request to map to response, present only when request contains req_id.
  int reqId;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
