/// Autogenerated from flutter_deriv_api|lib/api/new_account_maltainvest_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'new_account_maltainvest_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class NewAccountMaltainvestRequest {
  NewAccountMaltainvestRequest();
  factory NewAccountMaltainvestRequest.fromJson(Map<String, dynamic> json) =>
      _$NewAccountMaltainvestRequestFromJson(json);
  Map<String, dynamic> toJson() => _$NewAccountMaltainvestRequestToJson(this);

  // Properties
  int newAccountMaltainvest;

  /// Must be 1
  int acceptRisk;

  /// Show whether client has accepted risk disclaimer, boolean value 1 or 0
  String accountOpeningReason;

  /// Purpose and reason for requesting the account opening
  String accountTurnover;

  /// The anticipated account turnover
  String addressCity;

  /// Within 35 characters
  String addressLine1;

  /// Within 70 characters.
  String addressLine2;

  /// Optional field, within 70 characters.
  String addressPostcode;

  /// Optional field, within 20 characters and may not contain '+'.
  String addressState;

  /// Optional field, possible value receive from states_list call.
  String affiliateToken;

  /// Affiliate token, within 32 characters.
  String binaryOptionsTradingExperience;

  /// Binary options trading experience
  String binaryOptionsTradingFrequency;

  /// Binary options trading frequency
  String cfdTradingExperience;

  /// CFDs trading experience
  String cfdTradingFrequency;

  /// CFDs trading frequency
  String citizen;

  /// Country of legal citizenship, 2-letter country code.
  String clientType;

  /// Optional field, indicates whether this is for a client requesting an account with professional status. Defaults to retail.
  String dateOfBirth;

  /// Date of birth format: yyyy-mm-dd.
  String educationLevel;

  /// Level of Education
  String employmentIndustry;

  /// Industry of Employment
  String employmentStatus;

  /// Employment Status
  String estimatedWorth;

  /// Estimated Net Worth
  String firstName;

  /// Within 2-50 characters, use only letters, spaces, hyphens, full-stops or apostrophes.
  String forexTradingExperience;

  /// Forex trading experience
  String forexTradingFrequency;

  /// Forex trading frequency
  String incomeSource;

  /// Income Source
  String lastName;

  /// Within 2-50 characters, use only letters, spaces, hyphens, full-stops or apostrophes.
  String netIncome;

  /// Net Annual Income
  String occupation;

  /// Occupation
  String otherInstrumentsTradingExperience;

  /// Trading experience in other financial instruments
  String otherInstrumentsTradingFrequency;

  /// Trading frequency in other financial instruments
  String phone;

  /// Within 8-35 digits, allowing '+' in front, numbers, hyphens or space.
  String placeOfBirth;

  /// Place of birth, 2-letter country code.
  String residence;

  /// 2-letter country code, possible value receive from residence_list call.
  String salutation;

  /// Accept any value in enum list.
  String secretAnswer;

  /// Answer to secret question, within 4-50 characters.
  String secretQuestion;

  /// Accept any value in enum list.
  String sourceOfWealth;

  /// Source of wealth
  String taxIdentificationNumber;

  /// Tax identification number. Only applicable for real money account. Required for maltainvest landing company.
  String taxResidence;

  /// Residence for tax purpose. Comma separated iso country code if multiple jurisdictions. Only applicable for real money account. Required for maltainvest landing company.
  Map<String, dynamic> passthrough;

  /// [Optional] Used to pass data through the websocket, which may be retrieved via the echo_req output field.
  int reqId;

  /// [Optional] Used to map request to response.

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
