/// Autogenerated from flutter_deriv_api|lib/api/oauth_apps_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'oauth_apps_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class OauthAppsRequest {
  OauthAppsRequest();
  factory OauthAppsRequest.fromJson(Map<String, dynamic> json) =>
      _$OauthAppsRequestFromJson(json);
  Map<String, dynamic> toJson() => _$OauthAppsRequestToJson(this);

  // Properties
  int oauthApps;

  /// Must be 1
  Map<String, dynamic> passthrough;

  /// [Optional] Used to pass data through the websocket, which may be retrieved via the echo_req output field.
  int reqId;

  /// [Optional] Used to map request to response.

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
