/// Autogenerated from flutter_deriv_api|lib/api/oauth_apps_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'oauth_apps_receive.g.dart';

/// JSON conversion for 'oauth_apps_receive'
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class OauthAppsResponse extends Response {
  /// Initialize OauthAppsResponse
  OauthAppsResponse(
      {this.oauthApps,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Factory constructor to initialize from JSON
  factory OauthAppsResponse.fromJson(Map<String, dynamic> json) =>
      _$OauthAppsResponseFromJson(json);

  // Properties
  /// List of OAuth applications that used for the authorized account.
  List<Map<String, dynamic>> oauthApps;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$OauthAppsResponseToJson(this);
}
