/// Autogenerated from flutter_deriv_api|lib/api/p2p_advertiser_adverts_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'p2p_advertiser_adverts_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class P2pAdvertiserAdvertsRequest extends Request {
  ///
  P2pAdvertiserAdvertsRequest(
      {this.limit,
      this.offset,
      this.p2pAdvertiserAdverts,
      Map<String, dynamic> passthrough,
      int reqId})
      : super(passthrough: passthrough, reqId: reqId);

  ///
  factory P2pAdvertiserAdvertsRequest.fromJson(Map<String, dynamic> json) =>
      _$P2pAdvertiserAdvertsRequestFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$P2pAdvertiserAdvertsRequestToJson(this);

  // Properties
  /// [Optional] Used for paging.
  int limit;

  /// [Optional] Used for paging.
  int offset;

  /// Must be 1
  int p2pAdvertiserAdverts;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
