/// Autogenerated from flutter_deriv_api|lib/api/p2p_order_confirm_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'p2p_order_confirm_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class P2pOrderConfirmResponse extends Response {
  ///
  P2pOrderConfirmResponse(
      {Map<String, dynamic> echoReq,
      String msgType,
      this.p2pOrderConfirm,
      int reqId})
      : super(echoReq: echoReq, msgType: msgType, reqId: reqId);

  ///
  factory P2pOrderConfirmResponse.fromJson(Map<String, dynamic> json) =>
      _$P2pOrderConfirmResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$P2pOrderConfirmResponseToJson(this);

  // Properties

  /// Confirmation details
  Map<String, dynamic> p2pOrderConfirm;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
