/// Autogenerated from flutter_deriv_api|lib/api/p2p_advert_list_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'p2p_advert_list_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class P2pAdvertListRequest extends Request {
  ///
  P2pAdvertListRequest(
      {this.accountCurrency,
      this.advertiserId,
      this.amount,
      this.counterpartyType,
      this.country,
      this.limit,
      this.localCurrency,
      this.offset,
      this.p2pAdvertList,
      this.passthrough,
      this.reqId});

  ///
  factory P2pAdvertListRequest.fromJson(Map<String, dynamic> json) =>
      _$P2pAdvertListRequestFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$P2pAdvertListRequestToJson(this);

  // Properties
  /// [Optional] Target currency, defaults to client account currency.
  String accountCurrency;

  /// [Optional] Which advertiser to list adverts for.
  String advertiserId;

  /// [Optional] How much to buy or sell, used to calculate prices.
  num amount;

  /// [Optional] Filter the adverts by `counterparty_type`.
  String counterpartyType;

  /// [Optional] Which country to find adverts from.
  String country;

  /// [Optional] Used for paging.
  int limit;

  /// [Optional] Currency to conduct payment transaction in, defaults to the main currency for the client's country.
  String localCurrency;

  /// [Optional] Used for paging.
  int offset;

  /// Must be 1
  int p2pAdvertList;

  /// [Optional] Used to pass data through the websocket, which may be retrieved via the `echo_req` output field.
  Map<String, dynamic> passthrough;

  /// [Optional] Used to map request to response.
  int reqId;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
