/// Autogenerated from flutter_deriv_api|lib/api/p2p_advert_create_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'p2p_advert_create_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class P2pAdvertCreateResponse extends Response {
  ///
  P2pAdvertCreateResponse(
      {this.p2pAdvertCreate,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Instance from JSON
  factory P2pAdvertCreateResponse.fromJson(Map<String, dynamic> json) =>
      _$P2pAdvertCreateResponseFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$P2pAdvertCreateResponseToJson(this);

  // Properties
  /// The information of the created P2P advert.
  Map<String, dynamic> p2pAdvertCreate;
}
