/// Autogenerated from flutter_deriv_api|lib/api/p2p_advert_create_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'p2p_advert_create_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class P2pAdvertCreateResponse extends Response {
  ///
  P2pAdvertCreateResponse(
      {Map<String, dynamic> echoReq,
      String msgType,
      this.p2pAdvertCreate,
      int reqId})
      : super(echoReq: echoReq, msgType: msgType, reqId: reqId);

  ///
  factory P2pAdvertCreateResponse.fromJson(Map<String, dynamic> json) =>
      _$P2pAdvertCreateResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$P2pAdvertCreateResponseToJson(this);

  // Properties

  /// The information of the created P2P advert.
  Map<String, dynamic> p2pAdvertCreate;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
