/// Autogenerated from flutter_deriv_api|lib/api/p2p_order_cancel_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'p2p_order_cancel_receive.g.dart';

/// JSON conversion for 'p2p_order_cancel_receive'
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class P2pOrderCancelResponse extends Response {
  /// Initialize P2pOrderCancelResponse
  P2pOrderCancelResponse(
      {this.p2pOrderCancel,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Factory constructor to initialize from JSON
  factory P2pOrderCancelResponse.fromJson(Map<String, dynamic> json) =>
      _$P2pOrderCancelResponseFromJson(json);

  // Properties
  /// Cancellation details
  Map<String, dynamic> p2pOrderCancel;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$P2pOrderCancelResponseToJson(this);
}
