/// Autogenerated from flutter_deriv_api|lib/api/p2p_order_confirm_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'p2p_order_confirm_send.g.dart';

/// JSON conversion for 'p2p_order_confirm_send'
@JsonSerializable(nullable: true, fieldRename: FieldRename.snake)
class P2pOrderConfirmRequest extends Request {
  /// Initialize P2pOrderConfirmRequest
  P2pOrderConfirmRequest(
      {this.id,
      this.p2pOrderConfirm = 1,
      int reqId,
      Map<String, dynamic> passthrough})
      : super(reqId: reqId, passthrough: passthrough);

  /// Factory constructor to initialize from JSON
  factory P2pOrderConfirmRequest.fromJson(Map<String, dynamic> json) =>
      _$P2pOrderConfirmRequestFromJson(json);

  // Properties
  /// The unique identifier for this order.
  String id;

  /// Must be 1
  int p2pOrderConfirm;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$P2pOrderConfirmRequestToJson(this);
}
