/// Autogenerated from flutter_deriv_api|lib/api/p2p_order_cancel_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'p2p_order_cancel_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class P2pOrderCancelResponse extends Response {
  ///
  P2pOrderCancelResponse(
      {Map<String, dynamic> echoReq,
      String msgType,
      this.p2pOrderCancel,
      int reqId})
      : super(echoReq: echoReq, msgType: msgType, reqId: reqId);

  ///
  factory P2pOrderCancelResponse.fromJson(Map<String, dynamic> json) =>
      _$P2pOrderCancelResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$P2pOrderCancelResponseToJson(this);

  // Properties

  /// Cancellation details
  Map<String, dynamic> p2pOrderCancel;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
