/// Autogenerated from flutter_deriv_api|lib/api/p2p_order_create_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'p2p_order_create_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class P2pOrderCreateResponse extends Response {
  ///
  P2pOrderCreateResponse(
      {Map<String, dynamic> echoReq,
      String msgType,
      this.p2pOrderCreate,
      int reqId,
      this.subscription})
      : super(echoReq: echoReq, msgType: msgType, reqId: reqId);

  ///
  factory P2pOrderCreateResponse.fromJson(Map<String, dynamic> json) =>
      _$P2pOrderCreateResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$P2pOrderCreateResponseToJson(this);

  // Properties

  /// Information of the creates P2P order.
  Map<String, dynamic> p2pOrderCreate;

  /// For subscription requests only
  Map<String, dynamic> subscription;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
