/// Autogenerated from flutter_deriv_api|lib/api/p2p_order_list_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'p2p_order_list_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class P2pOrderListRequest {
  P2pOrderListRequest(
      {this.active,
      this.offerId,
      this.p2pOrderList,
      this.passthrough,
      this.reqId});
  factory P2pOrderListRequest.fromJson(Map<String, dynamic> json) =>
      _$P2pOrderListRequestFromJson(json);
  Map<String, dynamic> toJson() => _$P2pOrderListRequestToJson(this);

  // Properties
  /// [Optional] Should be 1 to list active, 0 to list inactive (historical).
  num active;

  /// [Optional] If present, lists orders applying to a specific offer.
  String offerId;

  /// Must be 1
  int p2pOrderList;

  /// [Optional] Used to pass data through the websocket, which may be retrieved via the `echo_req` output field.
  Map<String, dynamic> passthrough;

  /// [Optional] Used to map request to response.
  int reqId;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
