/// Autogenerated from flutter_deriv_api|lib/api/paymentagent_withdraw_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'paymentagent_withdraw_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class PaymentagentWithdrawRequest extends Request {
  ///
  PaymentagentWithdrawRequest(
      {this.amount,
      this.currency,
      this.description,
      this.dryRun,
      Map<String, dynamic> passthrough,
      this.paymentagentLoginid,
      this.paymentagentWithdraw,
      int reqId,
      this.verificationCode})
      : super(passthrough: passthrough, reqId: reqId);

  ///
  factory PaymentagentWithdrawRequest.fromJson(Map<String, dynamic> json) =>
      _$PaymentagentWithdrawRequestFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$PaymentagentWithdrawRequestToJson(this);

  // Properties
  /// The amount to withdraw to the payment agent.
  num amount;

  /// The currency code.
  String currency;

  /// [Optional] Remarks about the withdraw. Only letters, numbers, space, period, comma, - ' are allowed.
  String description;

  /// [Optional] If set to 1, just do validation.
  int dryRun;

  /// The payment agent loginid received from the `paymentagent_list` call.
  String paymentagentLoginid;

  /// Must be `1`
  int paymentagentWithdraw;

  /// Email verification code (received from a `verify_email` call, which must be done first)
  String verificationCode;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
