/// Autogenerated from flutter_deriv_api|lib/api/paymentagent_transfer_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'paymentagent_transfer_receive.g.dart';

/// JSON conversion for 'paymentagent_transfer_receive'
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class PaymentagentTransferResponse extends Response {
  /// Initialize PaymentagentTransferResponse
  PaymentagentTransferResponse(
      {this.clientToFullName,
      this.clientToLoginid,
      this.paymentagentTransfer,
      this.transactionId,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Factory constructor to initialize from JSON
  factory PaymentagentTransferResponse.fromJson(Map<String, dynamic> json) =>
      _$PaymentagentTransferResponseFromJson(json);

  // Properties
  /// The `transfer_to` client full name
  String clientToFullName;

  /// The `transfer_to` client loginid
  String clientToLoginid;

  /// If set to `1`, transfer success. If set to `2`, dry-run success.
  int paymentagentTransfer;

  /// Reference ID of transfer performed
  int transactionId;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$PaymentagentTransferResponseToJson(this);
}
