/// Autogenerated from flutter_deriv_api|lib/api/paymentagent_withdraw_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'paymentagent_withdraw_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class PaymentagentWithdrawResponse extends Response {
  ///
  PaymentagentWithdrawResponse(
      {Map<String, dynamic> echoReq,
      String msgType,
      this.paymentagentName,
      this.paymentagentWithdraw,
      int reqId,
      this.transactionId})
      : super(echoReq: echoReq, msgType: msgType, reqId: reqId);

  ///
  factory PaymentagentWithdrawResponse.fromJson(Map<String, dynamic> json) =>
      _$PaymentagentWithdrawResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$PaymentagentWithdrawResponseToJson(this);

  // Properties

  /// Payment agent name.
  String paymentagentName;

  /// If set to `1`, withdrawal success. If set to `2`, dry-run success.
  int paymentagentWithdraw;

  /// Reference ID of withdrawal performed.
  int transactionId;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
