/// Autogenerated from flutter_deriv_api|lib/api/paymentagent_withdraw_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'paymentagent_withdraw_send.g.dart';

/// JSON conversion for 'paymentagent_withdraw_send'
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class PaymentagentWithdrawRequest extends Request {
  /// Initialize PaymentagentWithdrawRequest
  PaymentagentWithdrawRequest(
      {this.amount,
      this.currency,
      this.description,
      this.dryRun,
      this.paymentagentLoginid,
      this.paymentagentWithdraw,
      this.verificationCode,
      int reqId,
      Map<String, dynamic> passthrough})
      : super(reqId: reqId, passthrough: passthrough);

  /// Factory constructor to initialize from JSON
  factory PaymentagentWithdrawRequest.fromJson(Map<String, dynamic> json) =>
      _$PaymentagentWithdrawRequestFromJson(json);

  // Properties
  /// The amount to withdraw to the payment agent.
  num amount;

  /// The currency code.
  String currency;

  /// [Optional] Remarks about the withdraw. Only letters, numbers, space, period, comma, - ' are allowed.
  String description;

  /// [Optional] If set to 1, just do validation.
  int dryRun;

  /// The payment agent loginid received from the `paymentagent_list` call.
  String paymentagentLoginid;

  /// Must be `1`
  int paymentagentWithdraw;

  /// Email verification code (received from a `verify_email` call, which must be done first)
  String verificationCode;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$PaymentagentWithdrawRequestToJson(this);
}
