/// Autogenerated from flutter_deriv_api|lib/api/payout_currencies_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'payout_currencies_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class PayoutCurrenciesResponse extends Response {
  ///
  PayoutCurrenciesResponse(
      {this.payoutCurrencies,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  ///
  factory PayoutCurrenciesResponse.fromJson(Map<String, dynamic> json) =>
      _$PayoutCurrenciesResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$PayoutCurrenciesResponseToJson(this);

  // Properties

  /// Available payout currencies. Note: if a user is logged in, only the currency available for the account will be returned.
  List<String> payoutCurrencies;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
