/// Autogenerated from flutter_deriv_api|lib/api/ping_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'ping_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class PingRequest {
  PingRequest({this.passthrough, this.ping, this.reqId});
  factory PingRequest.fromJson(Map<String, dynamic> json) =>
      _$PingRequestFromJson(json);
  Map<String, dynamic> toJson() => _$PingRequestToJson(this);

  // Properties
  /// [Optional] Used to pass data through the websocket, which may be retrieved via the `echo_req` output field.
  Map<String, dynamic> passthrough;

  /// Must be `1`
  int ping;

  /// [Optional] Used to map request to response.
  int reqId;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
