/// Autogenerated from flutter_deriv_api|lib/api/ping_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'ping_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class PingRequest extends Request {
  ///
  PingRequest({Map<String, dynamic> passthrough, this.ping, int reqId})
      : super(passthrough: passthrough, reqId: reqId);

  ///
  factory PingRequest.fromJson(Map<String, dynamic> json) =>
      _$PingRequestFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$PingRequestToJson(this);

  // Properties

  /// Must be `1`
  int ping;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
