/// Autogenerated from flutter_deriv_api|lib/api/ping_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'ping_send.g.dart';

/// JSON conversion for 'ping_send'
@JsonSerializable(nullable: true, fieldRename: FieldRename.snake)
class PingRequest extends Request {
  /// Initialize PingRequest
  PingRequest({this.ping = 1, int reqId, Map<String, dynamic> passthrough})
      : super(reqId: reqId, passthrough: passthrough);

  /// Factory constructor to initialize from JSON
  factory PingRequest.fromJson(Map<String, dynamic> json) =>
      _$PingRequestFromJson(json);

  // Properties
  /// Must be `1`
  int ping;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$PingRequestToJson(this);
}
