/// Autogenerated from flutter_deriv_api|lib/api/portfolio_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'portfolio_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class PortfolioRequest extends Request {
  ///
  PortfolioRequest({this.passthrough, this.portfolio, this.reqId});

  ///
  factory PortfolioRequest.fromJson(Map<String, dynamic> json) =>
      _$PortfolioRequestFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$PortfolioRequestToJson(this);

  // Properties
  /// [Optional] Used to pass data through the websocket, which may be retrieved via the `echo_req` output field.
  Map<String, dynamic> passthrough;

  /// Must be `1`
  int portfolio;

  /// [Optional] Used to map request to response.
  int reqId;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
