/// Autogenerated from flutter_deriv_api|lib/api/portfolio_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'portfolio_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class PortfolioRequest extends Request {
  ///
  PortfolioRequest(
      {this.portfolio, int reqId, Map<String, dynamic> passthrough})
      : super(reqId: reqId, passthrough: passthrough);

  /// Instance from JSON
  factory PortfolioRequest.fromJson(Map<String, dynamic> json) =>
      _$PortfolioRequestFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$PortfolioRequestToJson(this);

  // Properties
  /// Must be `1`
  int portfolio;
}
