/// Autogenerated from flutter_deriv_api|lib/api/portfolio_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'portfolio_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class PortfolioResponse extends Response {
  ///
  PortfolioResponse(
      {Map<String, dynamic> echoReq, String msgType, this.portfolio, int reqId})
      : super(echoReq: echoReq, msgType: msgType, reqId: reqId);

  ///
  factory PortfolioResponse.fromJson(Map<String, dynamic> json) =>
      _$PortfolioResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$PortfolioResponseToJson(this);

  // Properties

  /// Current account's open positions.
  Map<String, dynamic> portfolio;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
