/// Autogenerated from flutter_deriv_api|lib/api/profit_table_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'profit_table_receive.g.dart';

/// JSON conversion for 'profit_table_receive'
@JsonSerializable(nullable: true, fieldRename: FieldRename.snake)
class ProfitTableResponse extends Response {
  /// Initialize ProfitTableResponse
  ProfitTableResponse(
      {this.profitTable,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Factory constructor to initialize from JSON
  factory ProfitTableResponse.fromJson(Map<String, dynamic> json) =>
      _$ProfitTableResponseFromJson(json);

  // Properties
  /// Account Profit Table.
  Map<String, dynamic> profitTable;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$ProfitTableResponseToJson(this);
}
