/// Autogenerated from flutter_deriv_api|lib/api/profit_table_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'profit_table_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ProfitTableResponse extends Response {
  ///
  ProfitTableResponse(
      {this.echoReq, this.msgType, this.profitTable, this.reqId});

  ///
  factory ProfitTableResponse.fromJson(Map<String, dynamic> json) =>
      _$ProfitTableResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$ProfitTableResponseToJson(this);

  // Properties
  /// Echo of the request made.
  Map<String, dynamic> echoReq;

  /// Action name of the request made.
  String msgType;

  /// Account Profit Table.
  Map<String, dynamic> profitTable;

  /// Optional field sent in request to map to response, present only when request contains `req_id`.
  int reqId;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
