/// Autogenerated from flutter_deriv_api|lib/api/proposal_open_contract_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'proposal_open_contract_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ProposalOpenContractRequest {
  ProposalOpenContractRequest();
  factory ProposalOpenContractRequest.fromJson(Map<String, dynamic> json) =>
      _$ProposalOpenContractRequestFromJson(json);
  Map<String, dynamic> toJson() => _$ProposalOpenContractRequestToJson(this);

  // Properties
  int proposalOpenContract;

  /// Must be 1
  int contractId;

  /// Contract ID received from a Portfolio request. If not set, you will receive stream of all open contracts.
  int subscribe;

  /// 1 - to stream
  Map<String, dynamic> passthrough;

  /// [Optional] Used to pass data through the websocket, which may be retrieved via the echo_req output field.
  int reqId;

  /// [Optional] Used to map request to response.

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
