/// Autogenerated from flutter_deriv_api|lib/api/proposal_array_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'proposal_array_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ProposalArrayRequest {
  ProposalArrayRequest();
  factory ProposalArrayRequest.fromJson(Map<String, dynamic> json) =>
      _$ProposalArrayRequestFromJson(json);
  Map<String, dynamic> toJson() => _$ProposalArrayRequestToJson(this);

  // Properties
  int proposalArray;

  /// Must be 1
  num amount;

  /// Proposed contract payout or stake value.
  List<String> barriers;

  /// Array of barrier(s) for the contract.
  String basis;

  /// Indicate whether amount is 'payout' or 'stake'.
  List<String> contractType;

  /// One or two valid contract-types.
  String currency;

  /// This can only be the account-holder's currency.
  int dateExpiry;

  /// Epoch value of the expiry time of the contract. You must either specify date_expiry or duration.
  int dateStart;

  /// [Optional] Indicates epoch value of the starting time of the contract. If left empty, the start time of the contract is now.
  int duration;

  /// Duration quantity.
  String durationUnit;

  /// [Optional] Duration unit - s(seconds), m(minutes), h(hours), d(days), t(ticks).
  num multiplier;

  /// The multiplier for non-binary options. E.g. lookbacks.
  String productType;

  /// [Optional] If you specify this field, only contracts tradable through that contract type will be returned.
  int subscribe;

  /// [Optional] 1 - to initiate a realtime stream of prices. Note that tick trades (without a user-defined barrier), digit trades and less than 24 hours at-the-money contracts for the following underlying symbols are not streamed: R_10, R_25, R_50, R_75, R_100, RDBULL, RDBEAR (this is because their price is constant).
  String symbol;

  /// Symbol code.
  int tradingPeriodStart;

  /// Required only for multi-barrier trading. Defines the epoch value of the trading period start time.
  Map<String, dynamic> passthrough;

  /// [Optional] Used to pass data through the websocket, which may be retrieved via the echo_req output field.
  int reqId;

  /// [Optional] Used to map request to response.

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
