/// Autogenerated from flutter_deriv_api|lib/api/reality_check_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'reality_check_receive.g.dart';

/// JSON conversion for 'reality_check_receive'
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class RealityCheckResponse extends Response {
  /// Initialize RealityCheckResponse
  RealityCheckResponse(
      {this.realityCheck,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Factory constructor to initialize from JSON
  factory RealityCheckResponse.fromJson(Map<String, dynamic> json) =>
      _$RealityCheckResponseFromJson(json);

  // Properties
  /// Reality check summary of trades.
  Map<String, dynamic> realityCheck;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$RealityCheckResponseToJson(this);
}
