/// Autogenerated from flutter_deriv_api|lib/api/reality_check_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'reality_check_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class RealityCheckRequest {
  RealityCheckRequest({this.passthrough, this.realityCheck, this.reqId});
  factory RealityCheckRequest.fromJson(Map<String, dynamic> json) =>
      _$RealityCheckRequestFromJson(json);
  Map<String, dynamic> toJson() => _$RealityCheckRequestToJson(this);

  // Properties
  /// [Optional] Used to pass data through the websocket, which may be retrieved via the `echo_req` output field.
  Map<String, dynamic> passthrough;

  /// Must be `1`
  int realityCheck;

  /// [Optional] Used to map request to response.
  int reqId;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
