/// Autogenerated from flutter_deriv_api|lib/api/request_report_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'request_report_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class RequestReportResponse extends Response {
  ///
  RequestReportResponse(
      {this.requestReport,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Instance from JSON
  factory RequestReportResponse.fromJson(Map<String, dynamic> json) =>
      _$RequestReportResponseFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$RequestReportResponseToJson(this);

  // Properties
  /// Response of request report
  Map<String, dynamic> requestReport;
}
