/// Autogenerated from flutter_deriv_api|lib/api/request_report_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'request_report_receive.g.dart';

/// JSON conversion for 'request_report_receive'
@JsonSerializable(nullable: true, fieldRename: FieldRename.snake)
class RequestReportResponse extends Response {
  /// Initialize RequestReportResponse
  RequestReportResponse(
      {this.requestReport,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Factory constructor to initialize from JSON
  factory RequestReportResponse.fromJson(Map<String, dynamic> json) =>
      _$RequestReportResponseFromJson(json);

  // Properties
  /// Response of request report
  Map<String, dynamic> requestReport;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$RequestReportResponseToJson(this);
}
