/// Autogenerated from flutter_deriv_api|lib/api/request_report_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'request_report_receive.g.dart';

/// JSON conversion for 'request_report_receive'
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class RequestReportResponse extends Response {
  /// Initialize RequestReportResponse
  RequestReportResponse({
    this.requestReport,
    Map<String, dynamic> echoReq,
    Map<String, dynamic> error,
    String msgType,
    int reqId,
  }) : super(
          echoReq: echoReq,
          error: error,
          msgType: msgType,
          reqId: reqId,
        );

  /// Creates instance from JSON
  factory RequestReportResponse.fromJson(Map<String, dynamic> json) =>
      _$RequestReportResponseFromJson(json);

  // Properties
  /// Response of request report
  Map<String, dynamic> requestReport;

  /// Converts to JSON
  @override
  Map<String, dynamic> toJson() => _$RequestReportResponseToJson(this);
}
