/// Autogenerated from flutter_deriv_api|lib/api/reset_password_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'reset_password_receive.g.dart';

/// JSON conversion for 'reset_password_receive'
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ResetPasswordResponse extends Response {
  /// Initialize ResetPasswordResponse
  ResetPasswordResponse(
      {this.resetPassword,
      Map<String, dynamic> echoReq,
      Map<String, dynamic> error,
      String msgType,
      int reqId})
      : super(echoReq: echoReq, error: error, msgType: msgType, reqId: reqId);

  /// Creates instance from JSON
  factory ResetPasswordResponse.fromJson(Map<String, dynamic> json) =>
      _$ResetPasswordResponseFromJson(json);

  // Properties
  /// `1`: password reset success, `0`: password reset failure
  int resetPassword;

  /// Converts to JSON
  @override
  Map<String, dynamic> toJson() => _$ResetPasswordResponseToJson(this);
}
