/// Autogenerated from flutter_deriv_api|lib/api/reset_password_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'reset_password_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ResetPasswordResponse extends Response {
  ///
  ResetPasswordResponse(
      {this.resetPassword,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Instance from JSON
  factory ResetPasswordResponse.fromJson(Map<String, dynamic> json) =>
      _$ResetPasswordResponseFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$ResetPasswordResponseToJson(this);

  // Properties
  /// `1`: password reset success, `0`: password reset failure
  int resetPassword;
}
