/// Autogenerated from flutter_deriv_api|lib/api/residence_list_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'residence_list_send.g.dart';

/// JSON conversion for 'residence_list_send'
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ResidenceListRequest extends Request {
  /// Initialize ResidenceListRequest
  ResidenceListRequest({
    this.residenceList = 1,
    Map<String, dynamic> passthrough,
    int reqId,
  }) : super(
          msgType: 'residence_list',
          passthrough: passthrough,
          reqId: reqId,
        );

  /// Creates instance from JSON
  factory ResidenceListRequest.fromJson(Map<String, dynamic> json) =>
      _$ResidenceListRequestFromJson(json);

  // Properties
  /// Must be `1`
  int residenceList;

  /// Converts to JSON
  @override
  Map<String, dynamic> toJson() => _$ResidenceListRequestToJson(this);
}
