/// Autogenerated from flutter_deriv_api|lib/api/residence_list_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'residence_list_receive.g.dart';

/// JSON conversion for 'residence_list_receive'
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ResidenceListResponse extends Response {
  /// Initialize ResidenceListResponse
  ResidenceListResponse(
      {this.residenceList,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Factory constructor to initialize from JSON
  factory ResidenceListResponse.fromJson(Map<String, dynamic> json) =>
      _$ResidenceListResponseFromJson(json);

  // Properties
  /// List of countries for account opening
  List<Map<String, dynamic>> residenceList;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$ResidenceListResponseToJson(this);
}
