/// Autogenerated from flutter_deriv_api|lib/api/residence_list_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'residence_list_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ResidenceListResponse extends Response {
  ///
  ResidenceListResponse(
      {Map<String, dynamic> echoReq,
      String msgType,
      int reqId,
      this.residenceList})
      : super(echoReq: echoReq, msgType: msgType, reqId: reqId);

  ///
  factory ResidenceListResponse.fromJson(Map<String, dynamic> json) =>
      _$ResidenceListResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$ResidenceListResponseToJson(this);

  // Properties

  /// List of countries for account opening
  List<Map<String, dynamic>> residenceList;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
