/// Autogenerated from flutter_deriv_api|lib/api/revoke_oauth_app_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'revoke_oauth_app_send.g.dart';

/// JSON conversion for 'revoke_oauth_app_send'
@JsonSerializable(nullable: true, fieldRename: FieldRename.snake)
class RevokeOauthAppRequest extends Request {
  /// Initialize RevokeOauthAppRequest
  RevokeOauthAppRequest(
      {this.revokeOauthApp = 1, int reqId, Map<String, dynamic> passthrough})
      : super(reqId: reqId, passthrough: passthrough);

  /// Factory constructor to initialize from JSON
  factory RevokeOauthAppRequest.fromJson(Map<String, dynamic> json) =>
      _$RevokeOauthAppRequestFromJson(json);

  // Properties
  /// The application ID to revoke.
  int revokeOauthApp;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$RevokeOauthAppRequestToJson(this);
}
