/// Autogenerated from flutter_deriv_api|lib/api/revoke_oauth_app_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'revoke_oauth_app_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class RevokeOauthAppRequest {
  RevokeOauthAppRequest({this.passthrough, this.reqId, this.revokeOauthApp});
  factory RevokeOauthAppRequest.fromJson(Map<String, dynamic> json) =>
      _$RevokeOauthAppRequestFromJson(json);
  Map<String, dynamic> toJson() => _$RevokeOauthAppRequestToJson(this);

  // Properties
  /// [Optional] Used to pass data through the websocket, which may be retrieved via the `echo_req` output field.
  Map<String, dynamic> passthrough;

  /// [Optional] Used to map request to response.
  int reqId;

  /// The application ID to revoke.
  int revokeOauthApp;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
