/// Autogenerated from flutter_deriv_api|lib/api/sell_contract_for_multiple_accounts_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'sell_contract_for_multiple_accounts_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class SellContractForMultipleAccountsRequest extends Request {
  ///
  SellContractForMultipleAccountsRequest(
      {Map<String, dynamic> passthrough,
      this.price,
      int reqId,
      this.sellContractForMultipleAccounts,
      this.shortcode,
      this.tokens})
      : super(passthrough: passthrough, reqId: reqId);

  ///
  factory SellContractForMultipleAccountsRequest.fromJson(
          Map<String, dynamic> json) =>
      _$SellContractForMultipleAccountsRequestFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() =>
      _$SellContractForMultipleAccountsRequestToJson(this);

  // Properties

  /// Minimum price at which to sell the contract, or `0` for 'sell at market'.
  num price;

  /// Must be `1`
  int sellContractForMultipleAccounts;

  /// An internal ID used to identify the contract which was originally bought. This is returned from the `buy` and `buy_contract_for_multiple_accounts` calls.
  String shortcode;

  /// Authorisation tokens which select the accounts to sell use for the affected accounts.
  List<String> tokens;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
