/// Autogenerated from flutter_deriv_api|lib/api/sell_expired_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'sell_expired_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class SellExpiredRequest extends Request {
  ///
  SellExpiredRequest(
      {this.sellExpired, int reqId, Map<String, dynamic> passthrough})
      : super(reqId: reqId, passthrough: passthrough);

  /// Instance from JSON
  factory SellExpiredRequest.fromJson(Map<String, dynamic> json) =>
      _$SellExpiredRequestFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$SellExpiredRequestToJson(this);

  // Properties
  /// Must be `1`
  int sellExpired;
}
