/// Autogenerated from flutter_deriv_api|lib/api/sell_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'sell_receive.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class SellResponse {
  SellResponse();
  factory SellResponse.fromJson(Map<String, dynamic> json) =>
      _$SellResponseFromJson(json);
  Map<String, dynamic> toJson() => _$SellResponseToJson(this);

  // Properties
  Map<String, dynamic> sell;

  /// Receipt for the transaction
  Map<String, dynamic> echoReq;

  /// Echo of the request made.
  String msgType;

  /// Action name of the request made.
  int reqId;

  /// Optional field sent in request to map to response, present only when request contains req_id.

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
