/// Autogenerated from flutter_deriv_api|lib/api/sell_expired_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'sell_expired_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class SellExpiredResponse extends Response {
  ///
  SellExpiredResponse(
      {this.sellExpired,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Instance from JSON
  factory SellExpiredResponse.fromJson(Map<String, dynamic> json) =>
      _$SellExpiredResponseFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$SellExpiredResponseToJson(this);

  // Properties
  /// Sell expired contract object containing count of contracts sold
  Map<String, dynamic> sellExpired;
}
