/// Autogenerated from flutter_deriv_api|lib/api/sell_expired_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'sell_expired_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class SellExpiredRequest extends Request {
  ///
  SellExpiredRequest(
      {Map<String, dynamic> passthrough, int reqId, this.sellExpired})
      : super(passthrough: passthrough, reqId: reqId);

  ///
  factory SellExpiredRequest.fromJson(Map<String, dynamic> json) =>
      _$SellExpiredRequestFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$SellExpiredRequestToJson(this);

  // Properties

  /// Must be `1`
  int sellExpired;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
