/// Autogenerated from flutter_deriv_api|lib/api/service_token_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'service_token_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ServiceTokenResponse extends Response {
  ///
  ServiceTokenResponse(
      {this.serviceToken,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Instance from JSON
  factory ServiceTokenResponse.fromJson(Map<String, dynamic> json) =>
      _$ServiceTokenResponseFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$ServiceTokenResponseToJson(this);

  // Properties
  /// The object containing the retrieved token
  Map<String, dynamic> serviceToken;
}
