/// Autogenerated from flutter_deriv_api|lib/api/service_token_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'service_token_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class ServiceTokenResponse extends Response {
  ///
  ServiceTokenResponse(
      {Map<String, dynamic> echoReq,
      String msgType,
      int reqId,
      this.serviceToken})
      : super(echoReq: echoReq, msgType: msgType, reqId: reqId);

  ///
  factory ServiceTokenResponse.fromJson(Map<String, dynamic> json) =>
      _$ServiceTokenResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$ServiceTokenResponseToJson(this);

  // Properties

  /// The object containing the retrieved token
  Map<String, dynamic> serviceToken;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
