/// Autogenerated from flutter_deriv_api|lib/api/set_settings_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'set_settings_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class SetSettingsResponse extends Response {
  ///
  SetSettingsResponse(
      {Map<String, dynamic> echoReq,
      String msgType,
      int reqId,
      this.setSettings})
      : super(echoReq: echoReq, msgType: msgType, reqId: reqId);

  ///
  factory SetSettingsResponse.fromJson(Map<String, dynamic> json) =>
      _$SetSettingsResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$SetSettingsResponseToJson(this);

  // Properties

  /// 1 on success
  int setSettings;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
