/// Autogenerated from flutter_deriv_api|lib/api/set_self_exclusion_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'set_self_exclusion_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class SetSelfExclusionRequest {
  SetSelfExclusionRequest();
  factory SetSelfExclusionRequest.fromJson(Map<String, dynamic> json) =>
      _$SetSelfExclusionRequestFromJson(json);
  Map<String, dynamic> toJson() => _$SetSelfExclusionRequestToJson(this);

  // Properties
  /// Exclude me from the website (for a minimum of 6 months, up to a maximum of 5 years). Note: uplifting this self-exclusion may require contacting the company.
  String excludeUntil;

  /// 30-day limit on losses
  String max30dayLosses;

  /// 30-day turnover limit
  String max30dayTurnover;

  /// 7-day limit on losses
  String max7dayLosses;

  /// 7-day turnover limit
  String max7dayTurnover;

  /// Maximum account cash balance
  String maxBalance;

  /// Deposit limit.
  String maxDeposit;

  /// Exclude me from making deposits when the cumulative sum of deposits exceeds specified deposit limit.
  String maxDepositEndDate;

  /// Daily limit on losses
  String maxLosses;

  /// Maximum number of open positions
  String maxOpenBets;

  /// Daily turnover limit
  String maxTurnover;

  /// [Optional] Used to pass data through the websocket, which may be retrieved via the echo_req output field.
  Map<String, dynamic> passthrough;

  /// [Optional] Used to map request to response.
  int reqId;

  /// Session duration limit, in minutes
  String sessionDurationLimit;

  /// Must be 1
  int setSelfExclusion;

  /// Exclude me from the website (for up to 6 weeks). Requires time in epoch format. Note: unlike exclude_until, this self-exclusion will be lifted automatically at the expiry of the timeout period.
  String timeoutUntil;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
