/// Autogenerated from flutter_deriv_api|lib/api/set_account_currency_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'set_account_currency_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class SetAccountCurrencyResponse extends Response {
  ///
  SetAccountCurrencyResponse(
      {this.setAccountCurrency,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Instance from JSON
  factory SetAccountCurrencyResponse.fromJson(Map<String, dynamic> json) =>
      _$SetAccountCurrencyResponseFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$SetAccountCurrencyResponseToJson(this);

  // Properties
  /// `1`: success, `0`: no change
  int setAccountCurrency;
}
