/// Autogenerated from flutter_deriv_api|lib/api/set_self_exclusion_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'set_self_exclusion_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class SetSelfExclusionResponse extends Response {
  ///
  SetSelfExclusionResponse(
      {Map<String, dynamic> echoReq,
      String msgType,
      int reqId,
      this.setSelfExclusion})
      : super(echoReq: echoReq, msgType: msgType, reqId: reqId);

  ///
  factory SetSelfExclusionResponse.fromJson(Map<String, dynamic> json) =>
      _$SetSelfExclusionResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$SetSelfExclusionResponseToJson(this);

  // Properties

  /// `1` on success
  int setSelfExclusion;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
