/// Autogenerated from flutter_deriv_api|lib/api/set_settings_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'set_settings_receive.g.dart';

/// JSON conversion for 'set_settings_receive'
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class SetSettingsResponse extends Response {
  /// Initialize SetSettingsResponse
  SetSettingsResponse(
      {this.setSettings,
      Map<String, dynamic> echoReq,
      Map<String, dynamic> error,
      String msgType,
      int reqId})
      : super(echoReq: echoReq, error: error, msgType: msgType, reqId: reqId);

  /// Creates instance from JSON
  factory SetSettingsResponse.fromJson(Map<String, dynamic> json) =>
      _$SetSettingsResponseFromJson(json);

  // Properties
  /// 1 on success
  int setSettings;

  /// Converts to JSON
  @override
  Map<String, dynamic> toJson() => _$SetSettingsResponseToJson(this);
}
