/// Autogenerated from flutter_deriv_api|lib/api/statement_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'statement_receive.g.dart';

/// JSON conversion for 'statement_receive'
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class StatementResponse extends Response {
  /// Initialize StatementResponse
  StatementResponse(
      {this.statement,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Factory constructor to initialize from JSON
  factory StatementResponse.fromJson(Map<String, dynamic> json) =>
      _$StatementResponseFromJson(json);

  // Properties
  /// Account statement.
  Map<String, dynamic> statement;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$StatementResponseToJson(this);
}
