/// Autogenerated from flutter_deriv_api|lib/api/statement_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'statement_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class StatementRequest extends Request {
  ///
  StatementRequest(
      {this.actionType,
      this.dateFrom,
      this.dateTo,
      this.description,
      this.limit,
      this.offset,
      this.statement,
      int reqId,
      Map<String, dynamic> passthrough})
      : super(reqId: reqId, passthrough: passthrough);

  /// Instance from JSON
  factory StatementRequest.fromJson(Map<String, dynamic> json) =>
      _$StatementRequestFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$StatementRequestToJson(this);

  // Properties
  /// [Optional] To filter the statement according to the type of transaction.
  String actionType;

  /// [Optional] Start date (epoch)
  int dateFrom;

  /// [Optional] End date (epoch)
  int dateTo;

  /// [Optional] If set to 1, will return full contracts description.
  int description;

  /// [Optional] Maximum number of transactions to receive.
  num limit;

  /// [Optional] Number of transactions to skip.
  num offset;

  /// Must be `1`
  int statement;
}
