/// Autogenerated from flutter_deriv_api|lib/api/statement_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'statement_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class StatementResponse extends Response {
  ///
  StatementResponse({this.echoReq, this.msgType, this.reqId, this.statement});

  ///
  factory StatementResponse.fromJson(Map<String, dynamic> json) =>
      _$StatementResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$StatementResponseToJson(this);

  // Properties
  /// Echo of the request made.
  Map<String, dynamic> echoReq;

  /// Action name of the request made.
  String msgType;

  /// Optional field sent in request to map to response, present only when request contains `req_id`.
  int reqId;

  /// Account statement.
  Map<String, dynamic> statement;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
