/// Autogenerated from flutter_deriv_api|lib/api/ticks_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'ticks_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class TicksResponse extends Response {
  ///
  TicksResponse(
      {Map<String, dynamic> echoReq,
      String msgType,
      int reqId,
      this.subscription,
      this.tick})
      : super(echoReq: echoReq, msgType: msgType, reqId: reqId);

  ///
  factory TicksResponse.fromJson(Map<String, dynamic> json) =>
      _$TicksResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$TicksResponseToJson(this);

  // Properties

  /// For subscription requests only
  Map<String, dynamic> subscription;

  /// Tick by tick list of streamed data
  Map<String, dynamic> tick;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
