/// Autogenerated from flutter_deriv_api|lib/api/ticks_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'ticks_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class TicksRequest {
  TicksRequest({this.passthrough, this.reqId, this.subscribe, this.ticks});
  factory TicksRequest.fromJson(Map<String, dynamic> json) =>
      _$TicksRequestFromJson(json);
  Map<String, dynamic> toJson() => _$TicksRequestToJson(this);

  // Properties
  /// [Optional] Used to pass data through the websocket, which may be retrieved via the `echo_req` output field.
  Map<String, dynamic> passthrough;

  /// [Optional] Used to map request to response.
  int reqId;

  /// [Optional] If set to 1, will send updates whenever a new tick is received.
  int subscribe;

  /// The short symbol name or array of symbols (obtained from active_symbols call).
  String ticks;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
