/// Autogenerated from flutter_deriv_api|lib/api/ticks_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'ticks_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class TicksResponse extends Response {
  ///
  TicksResponse(
      {this.subscription,
      this.tick,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Instance from JSON
  factory TicksResponse.fromJson(Map<String, dynamic> json) =>
      _$TicksResponseFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$TicksResponseToJson(this);

  // Properties
  /// For subscription requests only
  Map<String, dynamic> subscription;

  /// Tick by tick list of streamed data
  Map<String, dynamic> tick;
}
