/// Autogenerated from flutter_deriv_api|lib/api/time_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'time_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class TimeResponse extends Response {
  ///
  TimeResponse(
      {this.time,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Instance from JSON
  factory TimeResponse.fromJson(Map<String, dynamic> json) =>
      _$TimeResponseFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$TimeResponseToJson(this);

  // Properties
  /// Epoch of server time.
  int time;
}
