/// Autogenerated from flutter_deriv_api|lib/api/tnc_approval_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'tnc_approval_receive.g.dart';

/// JSON conversion for 'tnc_approval_receive'
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class TncApprovalResponse extends Response {
  /// Initialize TncApprovalResponse
  TncApprovalResponse(
      {this.tncApproval,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Factory constructor to initialize from JSON
  factory TncApprovalResponse.fromJson(Map<String, dynamic> json) =>
      _$TncApprovalResponseFromJson(json);

  // Properties
  /// Set terms and conditions 1: success
  int tncApproval;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$TncApprovalResponseToJson(this);
}
