/// Autogenerated from flutter_deriv_api|lib/api/tnc_approval_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'tnc_approval_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class TncApprovalResponse extends Response {
  ///
  TncApprovalResponse(
      {Map<String, dynamic> echoReq,
      String msgType,
      int reqId,
      this.tncApproval})
      : super(echoReq: echoReq, msgType: msgType, reqId: reqId);

  ///
  factory TncApprovalResponse.fromJson(Map<String, dynamic> json) =>
      _$TncApprovalResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$TncApprovalResponseToJson(this);

  // Properties

  /// Set terms and conditions 1: success
  int tncApproval;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
