/// Autogenerated from flutter_deriv_api|lib/api/topup_virtual_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'topup_virtual_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class TopupVirtualRequest extends Request {
  ///
  TopupVirtualRequest(
      {Map<String, dynamic> passthrough, int reqId, this.topupVirtual})
      : super(passthrough: passthrough, reqId: reqId);

  ///
  factory TopupVirtualRequest.fromJson(Map<String, dynamic> json) =>
      _$TopupVirtualRequestFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$TopupVirtualRequestToJson(this);

  // Properties

  /// Must be `1`
  int topupVirtual;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
