/// Autogenerated from flutter_deriv_api|lib/api/trading_times_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'trading_times_receive.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class TradingTimesResponse {
  TradingTimesResponse(
      {this.echoReq, this.msgType, this.reqId, this.tradingTimes});
  factory TradingTimesResponse.fromJson(Map<String, dynamic> json) =>
      _$TradingTimesResponseFromJson(json);
  Map<String, dynamic> toJson() => _$TradingTimesResponseToJson(this);

  // Properties
  /// Echo of the request made.
  Map<String, dynamic> echoReq;

  /// Action name of the request made.
  String msgType;

  /// Optional field sent in request to map to response, present only when request contains `req_id`.
  int reqId;

  /// The trading times structure is a hierarchy as follows: Market -> SubMarket -> Underlyings
  Map<String, dynamic> tradingTimes;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
