/// Autogenerated from flutter_deriv_api|lib/api/trading_durations_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'trading_durations_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class TradingDurationsRequest {
  TradingDurationsRequest();
  factory TradingDurationsRequest.fromJson(Map<String, dynamic> json) =>
      _$TradingDurationsRequestFromJson(json);
  Map<String, dynamic> toJson() => _$TradingDurationsRequestToJson(this);

  // Properties
  int tradingDurations;

  /// Must be 1
  String landingCompany;

  /// [Optional] If specified, will return only the underlyings for the specified landing company.
  Map<String, dynamic> passthrough;

  /// [Optional] Used to pass data through the websocket, which may be retrieved via the echo_req output field.
  int reqId;

  /// [Optional] Used to map request to response.

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
