/// Autogenerated from flutter_deriv_api|lib/api/trading_times_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'trading_times_receive.g.dart';

/// JSON conversion for 'trading_times_receive'
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class TradingTimesResponse extends Response {
  /// Initialize TradingTimesResponse
  TradingTimesResponse(
      {this.tradingTimes,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Factory constructor to initialize from JSON
  factory TradingTimesResponse.fromJson(Map<String, dynamic> json) =>
      _$TradingTimesResponseFromJson(json);

  // Properties
  /// The trading times structure is a hierarchy as follows: Market -> SubMarket -> Underlyings
  Map<String, dynamic> tradingTimes;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$TradingTimesResponseToJson(this);
}
