/// Autogenerated from flutter_deriv_api|lib/api/trading_durations_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'trading_durations_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class TradingDurationsResponse extends Response {
  ///
  TradingDurationsResponse(
      {this.tradingDurations,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  ///
  factory TradingDurationsResponse.fromJson(Map<String, dynamic> json) =>
      _$TradingDurationsResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$TradingDurationsResponseToJson(this);

  // Properties

  /// List of underlyings by their display name and symbol followed by their available contract types and trading duration boundaries.
  List<Map<String, dynamic>> tradingDurations;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
