/// Autogenerated from flutter_deriv_api|lib/api/trading_durations_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'trading_durations_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class TradingDurationsRequest extends Request {
  ///
  TradingDurationsRequest(
      {this.landingCompany,
      this.tradingDurations,
      int reqId,
      Map<String, dynamic> passthrough})
      : super(reqId: reqId, passthrough: passthrough);

  /// Instance from JSON
  factory TradingDurationsRequest.fromJson(Map<String, dynamic> json) =>
      _$TradingDurationsRequestFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$TradingDurationsRequestToJson(this);

  // Properties
  /// [Optional] If specified, will return only the underlyings for the specified landing company.
  String landingCompany;

  /// Must be `1`
  int tradingDurations;
}
