/// Autogenerated from flutter_deriv_api|lib/api/transfer_between_accounts_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'transfer_between_accounts_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class TransferBetweenAccountsRequest extends Request {
  ///
  TransferBetweenAccountsRequest(
      {this.accountFrom,
      this.accountTo,
      this.accounts,
      this.amount,
      this.currency,
      this.transferBetweenAccounts,
      int reqId,
      Map<String, dynamic> passthrough})
      : super(reqId: reqId, passthrough: passthrough);

  ///
  factory TransferBetweenAccountsRequest.fromJson(Map<String, dynamic> json) =>
      _$TransferBetweenAccountsRequestFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$TransferBetweenAccountsRequestToJson(this);

  // Properties
  /// [Optional] The loginid of the account to transfer funds from.
  String accountFrom;

  /// [Optional] The loginid of the account to transfer funds to.
  String accountTo;

  /// [Optional] To control the list of accounts returned when `account_from` or `account_to` is not provided. `brief` will only include standard trading accounts and can be faster.
  String accounts;

  /// [Optional] The amount to transfer.
  num amount;

  /// [Optional] Currency code.
  String currency;

  /// If `account_from` or `account_to` is not provided, it just returns the available accounts.
  int transferBetweenAccounts;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
