/// Autogenerated from flutter_deriv_api|lib/api/transfer_between_accounts_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'transfer_between_accounts_send.g.dart';

/// JSON conversion for 'transfer_between_accounts_send'
@JsonSerializable(nullable: true, fieldRename: FieldRename.snake)
class TransferBetweenAccountsRequest extends Request {
  /// Initialize TransferBetweenAccountsRequest
  TransferBetweenAccountsRequest(
      {this.accountFrom,
      this.accountTo,
      this.accounts,
      this.amount,
      this.currency,
      this.transferBetweenAccounts = 1,
      Map<String, dynamic> passthrough,
      int reqId})
      : super(passthrough: passthrough, reqId: reqId);

  /// Creates instance from JSON
  factory TransferBetweenAccountsRequest.fromJson(Map<String, dynamic> json) =>
      _$TransferBetweenAccountsRequestFromJson(json);

  // Properties
  /// [Optional] The loginid of the account to transfer funds from.
  String accountFrom;

  /// [Optional] The loginid of the account to transfer funds to.
  String accountTo;

  /// [Optional] To control the list of accounts returned when `account_from` or `account_to` is not provided. `brief` will only include standard trading accounts and can be faster.
  String accounts;

  /// [Optional] The amount to transfer.
  num amount;

  /// [Optional] Currency code.
  String currency;

  /// If `account_from` or `account_to` is not provided, it just returns the available accounts.
  int transferBetweenAccounts;

  /// Converts to JSON
  @override
  Map<String, dynamic> toJson() => _$TransferBetweenAccountsRequestToJson(this);
}
