/// Autogenerated from flutter_deriv_api|lib/api/transfer_between_accounts_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'transfer_between_accounts_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class TransferBetweenAccountsResponse extends Response {
  ///
  TransferBetweenAccountsResponse(
      {this.accounts,
      this.clientToFullName,
      this.clientToLoginid,
      Map<String, dynamic> echoReq,
      String msgType,
      int reqId,
      this.transactionId,
      this.transferBetweenAccounts})
      : super(echoReq: echoReq, msgType: msgType, reqId: reqId);

  ///
  factory TransferBetweenAccountsResponse.fromJson(Map<String, dynamic> json) =>
      _$TransferBetweenAccountsResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() =>
      _$TransferBetweenAccountsResponseToJson(this);

  // Properties
  /// The available accounts to transfer, or the accounts affected by a successful transfer.
  List<Map<String, dynamic>> accounts;

  /// The account to client full name
  String clientToFullName;

  /// The account to client loginid
  String clientToLoginid;

  /// Reference ID of transfer performed
  int transactionId;

  /// If set to 1, transfer succeeded.
  int transferBetweenAccounts;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
