/// Autogenerated from flutter_deriv_api|lib/api/transaction_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'transaction_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class TransactionResponse extends Response {
  ///
  TransactionResponse(
      {Map<String, dynamic> echoReq,
      String msgType,
      int reqId,
      this.subscription,
      this.transaction})
      : super(echoReq: echoReq, msgType: msgType, reqId: reqId);

  ///
  factory TransactionResponse.fromJson(Map<String, dynamic> json) =>
      _$TransactionResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$TransactionResponseToJson(this);

  // Properties

  /// For subscription requests only
  Map<String, dynamic> subscription;

  /// Realtime stream of user transaction updates.
  Map<String, dynamic> transaction;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
