/// Autogenerated from flutter_deriv_api|lib/api/transaction_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'transaction_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class TransactionRequest extends Request {
  ///
  TransactionRequest(
      {this.passthrough, this.reqId, this.subscribe, this.transaction});

  ///
  factory TransactionRequest.fromJson(Map<String, dynamic> json) =>
      _$TransactionRequestFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$TransactionRequestToJson(this);

  // Properties
  /// [Optional] Used to pass data through the websocket, which may be retrieved via the `echo_req` output field.
  Map<String, dynamic> passthrough;

  /// [Optional] Used to map request to response.
  int reqId;

  /// If set to 1, will send updates whenever there is an update to transactions. If not to 1 then it will not return any records.
  int subscribe;

  /// Must be `1`
  int transaction;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
