/// Autogenerated from flutter_deriv_api|lib/api/transfer_between_accounts_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'transfer_between_accounts_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class TransferBetweenAccountsRequest {
  TransferBetweenAccountsRequest();
  factory TransferBetweenAccountsRequest.fromJson(Map<String, dynamic> json) =>
      _$TransferBetweenAccountsRequestFromJson(json);
  Map<String, dynamic> toJson() => _$TransferBetweenAccountsRequestToJson(this);

  // Properties
  int transferBetweenAccounts;

  /// If account_from or account_to is not provided, we'll just return available accounts.
  String accountFrom;

  /// The account_from loginid
  String accountTo;

  /// The account_to loginid
  String accounts;

  /// Optional field to control the list of accounts returned when account_from or account_to is not provided. 'Brief' will only include standard trading accounts and can be faster.
  num amount;

  /// The amount to transfer.
  String currency;

  /// Currency code
  Map<String, dynamic> passthrough;

  /// [Optional] Used to pass data through the websocket, which may be retrieved via the echo_req output field.
  int reqId;

  /// [Optional] Used to map request to response.

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
