/// Autogenerated from flutter_deriv_api|lib/api/transfer_between_accounts_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'transfer_between_accounts_receive.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class TransferBetweenAccountsResponse {
  TransferBetweenAccountsResponse();
  factory TransferBetweenAccountsResponse.fromJson(Map<String, dynamic> json) =>
      _$TransferBetweenAccountsResponseFromJson(json);
  Map<String, dynamic> toJson() =>
      _$TransferBetweenAccountsResponseToJson(this);

  // Properties
  int transferBetweenAccounts;

  /// If set to 1, transfer succeeded.
  List<String> accounts;

  /// The available accounts to transfer, or the accounts affected by a successful transfer.
  String clientToFullName;

  /// The account to client full name
  String clientToLoginid;

  /// The account to client loginid
  int transactionId;

  /// Reference ID of transfer performed
  Map<String, dynamic> echoReq;

  /// Echo of the request made.
  String msgType;

  /// Action name of the request made.
  int reqId;

  /// Optional field sent in request to map to response, present only when request contains req_id.

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
