/// Autogenerated from flutter_deriv_api|lib/api/transaction_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'transaction_send.g.dart';

/// JSON conversion for 'transaction_send'
@JsonSerializable(nullable: true, fieldRename: FieldRename.snake)
class TransactionRequest extends Request {
  /// Initialize TransactionRequest
  TransactionRequest(
      {this.subscribe,
      this.transaction = 1,
      int reqId,
      Map<String, dynamic> passthrough})
      : super(reqId: reqId, passthrough: passthrough);

  /// Factory constructor to initialize from JSON
  factory TransactionRequest.fromJson(Map<String, dynamic> json) =>
      _$TransactionRequestFromJson(json);

  // Properties
  /// If set to 1, will send updates whenever there is an update to transactions. If not to 1 then it will not return any records.
  int subscribe;

  /// Must be `1`
  int transaction;

  /// Converts this instance to JSON
  @override
  Map<String, dynamic> toJson() => _$TransactionRequestToJson(this);
}
