/// Autogenerated from flutter_deriv_api|lib/api/verify_email_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'verify_email_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class VerifyEmailResponse extends Response {
  ///
  VerifyEmailResponse(
      {this.verifyEmail,
      int reqId,
      Map<String, dynamic> echoReq,
      String msgType,
      Map<String, dynamic> error})
      : super(reqId: reqId, echoReq: echoReq, msgType: msgType, error: error);

  /// Instance from JSON
  factory VerifyEmailResponse.fromJson(Map<String, dynamic> json) =>
      _$VerifyEmailResponseFromJson(json);

  /// Instance to JSON
  @override
  Map<String, dynamic> toJson() => _$VerifyEmailResponseToJson(this);

  // Properties
  /// 1 for success (secure code has been sent to the email address)
  int verifyEmail;
}
