/// Autogenerated from flutter_deriv_api|lib/api/verify_email_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'verify_email_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class VerifyEmailResponse extends Response {
  ///
  VerifyEmailResponse(
      {Map<String, dynamic> echoReq,
      String msgType,
      int reqId,
      this.verifyEmail})
      : super(echoReq: echoReq, msgType: msgType, reqId: reqId);

  ///
  factory VerifyEmailResponse.fromJson(Map<String, dynamic> json) =>
      _$VerifyEmailResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$VerifyEmailResponseToJson(this);

  // Properties

  /// 1 for success (secure code has been sent to the email address)
  int verifyEmail;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
