/// Autogenerated from flutter_deriv_api|lib/api/verify_email_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'verify_email_receive.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class VerifyEmailResponse {
  VerifyEmailResponse(
      {this.echoReq, this.msgType, this.reqId, this.verifyEmail});
  factory VerifyEmailResponse.fromJson(Map<String, dynamic> json) =>
      _$VerifyEmailResponseFromJson(json);
  Map<String, dynamic> toJson() => _$VerifyEmailResponseToJson(this);

  // Properties
  /// Echo of the request made.
  Map<String, dynamic> echoReq;

  /// Action name of the request made.
  String msgType;

  /// Optional field sent in request to map to response, present only when request contains `req_id`.
  int reqId;

  /// 1 for success (secure code has been sent to the email address)
  int verifyEmail;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
