/// Autogenerated from flutter_deriv_api|lib/api/verify_email_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'verify_email_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class VerifyEmailRequest {
  VerifyEmailRequest();
  factory VerifyEmailRequest.fromJson(Map<String, dynamic> json) =>
      _$VerifyEmailRequestFromJson(json);
  Map<String, dynamic> toJson() => _$VerifyEmailRequestToJson(this);

  // Properties
  /// [Optional] Used to pass data through the websocket, which may be retrieved via the echo_req output field.
  Map<String, dynamic> passthrough;

  /// [Optional] Used to map request to response.
  int reqId;

  /// Purpose of the email verification call.
  String type;

  /// Extra parameters that can be attached to the verify email link url
  Map<String, dynamic> urlParameters;

  /// Email address to be verified.
  String verifyEmail;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
