/// Autogenerated from flutter_deriv_api|lib/api/verify_email_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'verify_email_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class VerifyEmailRequest extends Request {
  ///
  VerifyEmailRequest(
      {this.type,
      this.urlParameters,
      this.verifyEmail,
      int reqId,
      Map<String, dynamic> passthrough})
      : super(reqId: reqId, passthrough: passthrough);

  ///
  factory VerifyEmailRequest.fromJson(Map<String, dynamic> json) =>
      _$VerifyEmailRequestFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$VerifyEmailRequestToJson(this);

  // Properties

  /// Purpose of the email verification call.
  String type;

  /// [Optional] Extra parameters that can be attached to the verify email link URL.
  Map<String, dynamic> urlParameters;

  /// Email address to be verified.
  String verifyEmail;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
