/// Autogenerated from flutter_deriv_api|lib/api/website_status_receive.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'response.dart';

part 'website_status_receive.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class WebsiteStatusResponse extends Response {
  ///
  WebsiteStatusResponse(
      {Map<String, dynamic> echoReq,
      String msgType,
      int reqId,
      this.subscription,
      this.websiteStatus})
      : super(echoReq: echoReq, msgType: msgType, reqId: reqId);

  ///
  factory WebsiteStatusResponse.fromJson(Map<String, dynamic> json) =>
      _$WebsiteStatusResponseFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$WebsiteStatusResponseToJson(this);

  // Properties

  /// For subscription requests only
  Map<String, dynamic> subscription;

  /// Server status and other information regarding general settings
  Map<String, dynamic> websiteStatus;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
