/// Autogenerated from flutter_deriv_api|lib/api/website_status_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'website_status_send.g.dart';

@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class WebsiteStatusRequest {
  WebsiteStatusRequest(
      {this.passthrough, this.reqId, this.subscribe, this.websiteStatus});
  factory WebsiteStatusRequest.fromJson(Map<String, dynamic> json) =>
      _$WebsiteStatusRequestFromJson(json);
  Map<String, dynamic> toJson() => _$WebsiteStatusRequestToJson(this);

  // Properties
  /// [Optional] Used to pass data through the websocket, which may be retrieved via the `echo_req` output field.
  Map<String, dynamic> passthrough;

  /// [Optional] Used to map request to response.
  int reqId;

  /// [Optional] `1` to stream the server/website status updates.
  int subscribe;

  /// Must be `1`
  int websiteStatus;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
