/// Autogenerated from flutter_deriv_api|lib/api/website_status_send.json
import 'dart:async';
import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'request.dart';

part 'website_status_send.g.dart';

///
@JsonSerializable(nullable: false, fieldRename: FieldRename.snake)
class WebsiteStatusRequest extends Request {
  ///
  WebsiteStatusRequest(
      {this.subscribe,
      this.websiteStatus,
      int reqId,
      Map<String, dynamic> passthrough})
      : super(reqId: reqId, passthrough: passthrough);

  ///
  factory WebsiteStatusRequest.fromJson(Map<String, dynamic> json) =>
      _$WebsiteStatusRequestFromJson(json);

  ///
  @override
  Map<String, dynamic> toJson() => _$WebsiteStatusRequestToJson(this);

  // Properties

  /// [Optional] `1` to stream the server/website status updates.
  int subscribe;

  /// Must be `1`
  int websiteStatus;

  // @override
  // String toString() => name;
  static bool _fromInteger(int v) => (v != 0);
  static int _fromBoolean(bool v) => v ? 1 : 0;
}
