targets:
  $default:
    builders:
      flutter_deriv_api|api:
        enabled: true
        generate_for:
        - lib/api/*_send.json
        - lib/api/*_receive.json
builders:
  api:
    import: './api_builder.dart'
    builder_factories: ["apiBuilder"]
    auto_apply: root_package
    build_extensions: {".json": [".dart"]}
    is_optional: False
    build_to: source
    runs_before: ["json_serializable|json_serializable"]
    defaults:
      generate_for:
        include:
          - lib/api/**
    #applies_builders:
    #  - json_serializable|json_serializable
