version: 2
jobs:
  build:    
    docker:
      - image: cirrusci/flutter:stable

    steps:
      - checkout
      - run:
          name: Update submodules
          command: |
              git submodule init
              git submodule update --remote

      - run:
          name: Run Flutter doctor
          command: flutter doctor

      - run:
          name: Link JSON files for API autobuild
          command: ./setup.sh

      - run:
          name: pub get
          command: flutter pub get

      - run:
          name: Build step
          command: flutter pub run build_runner build

      - run:
          name: Run the application tests
          command: flutter test --coverage

      - run:
          name: Upload coverage
          command: |
              bash <(curl -s https://codecov.io/bash)

      - run:
          name: Code analysis
          command: |
              dartanalyzer --options analysis_options.yaml --fatal-warnings lib

      - restore_cache:
          keys:
              - android-sdk-licenses
              - gradle
              - pub-cache

      - run:
          name: Check that the package is ready for publishing
          command: flutter packages pub publish --dry-run

      - run:
          name: Check that the package is ready for publishing
          command: |
              cd example && flutter build apk

      - save_cache:
          key: android-sdk-licenses
          paths:
              - /opt/android-sdk-linux/licenses

      - save_cache:
          key: pub-cache
          paths:
              - /home/cirrus/.pub-cache

      - save_cache:
          key: gradle
          paths:
              - ~/.gradle

      - run:
          name: Copy APK
          command: |
              sudo mkdir -p /artifacts && sudo chown "$(whoami)" /artifacts && cp example/build/app/outputs/apk/release/app-release.apk /artifacts/deriv-api-example.apk

      - store_artifacts:
          path: /artifacts
