///
const List<Map<String, dynamic>> offerList = <Map<String, dynamic>>[
  <String, dynamic>{
    'account_currency': 'USD',
    'agent_id': '5',
    'agent_name': 'mock_name',
    'amount': 100,
    'amount_display': '100.00',
    'amount_used': 0,
    'amount_used_display': '0.00',
    'country': 'id',
    'created_time': 1577167966,
    'is_active': 1,
    'local_currency': 'IDR',
    'max_order_amount': 100,
    'max_order_amount_display': '100.00',
    'method': 'bank_transfer',
    'min_order_amount': 10,
    'min_order_amount_display': '10.00',
    'description': 'Please contact via whatsapp 1234',
    'offer_id': '9',
    'price': 14500,
    'price_display': '14500',
    'rate': 14500,
    'rate_display': '14500',
    'type': 'buy'
  },
  <String, dynamic>{
    'account_currency': 'USD',
    'agent_id': '3',
    'agent_name': 'mock_mun agent',
    'amount': 100,
    'amount_display': '100.00',
    'amount_used': 10.1,
    'amount_used_display': '10.10',
    'country': 'id',
    'created_time': 1577156942,
    'is_active': 1,
    'local_currency': 'IDR',
    'max_order_amount': 89.9,
    'max_order_amount_display': '89.90',
    'method': 'bank_transfer',
    'min_order_amount': 10,
    'min_order_amount_display': '10.00',
    'description': 'Please contact via whatsapp 1234',
    'offer_id': '5',
    'price': 14500,
    'price_display': '14500',
    'rate': 14500,
    'rate_display': '14500',
    'type': 'buy'
  },
  <String, dynamic>{
    'account_currency': 'USD',
    'agent_id': '4',
    'agent_name': 'mock_name',
    'amount': 100,
    'amount_display': '100.00',
    'amount_used': 0,
    'amount_used_display': '0.00',
    'country': 'id',
    'created_time': 1577159690,
    'is_active': 1,
    'local_currency': 'IDR',
    'max_order_amount': 100,
    'max_order_amount_display': '100.00',
    'method': 'bank_transfer',
    'min_order_amount': 10,
    'min_order_amount_display': '10.00',
    'description': 'Please contact via whatsapp 1234',
    'offer_id': '7',
    'price': 14500,
    'price_display': '14500',
    'rate': 14500,
    'rate_display': '14500',
    'type': 'buy'
  },
  <String, dynamic>{
    'account_currency': 'USD',
    'agent_id': '2',
    'agent_name': 'mock_name',
    'amount': 100,
    'amount_display': '100.00',
    'amount_used': 0,
    'amount_used_display': '0.00',
    'country': 'id',
    'created_time': 1577156519,
    'is_active': 1,
    'local_currency': 'IDR',
    'max_order_amount': 100,
    'max_order_amount_display': '100.00',
    'method': 'bank_transfer',
    'min_order_amount': 10,
    'min_order_amount_display': '10.00',
    'description': 'Please contact via whatsapp 1234',
    'offer_id': '3',
    'price': 14500,
    'price_display': '14500',
    'rate': 14500,
    'rate_display': '14500',
    'type': 'buy'
  },
  <String, dynamic>{
    'account_currency': 'USD',
    'agent_id': '1',
    'agent_name': 'mock_where is water',
    'amount': 100,
    'amount_display': '100.00',
    'amount_used': 21,
    'amount_used_display': '21.00',
    'country': 'id',
    'created_time': 1577155730,
    'is_active': 1,
    'local_currency': 'IDR',
    'max_order_amount': 79,
    'max_order_amount_display': '79.00',
    'method': 'bank_transfer',
    'min_order_amount': 10,
    'min_order_amount_display': '10.00',
    'description': 'Please contact via whatsapp 1234',
    'offer_id': '1',
    'price': 14500,
    'price_display': '14500',
    'rate': 14500,
    'rate_display': '14500',
    'type': 'buy'
  },
  <String, dynamic>{
    'account_currency': 'USD',
    'agent_id': '4',
    'agent_name': 'mock_name',
    'amount': 100,
    'amount_display': '100.00',
    'amount_used': 0,
    'amount_used_display': '0.00',
    'country': 'id',
    'created_time': 1577159690,
    'is_active': 1,
    'local_currency': 'IDR',
    'max_order_amount': 100,
    'max_order_amount_display': '100.00',
    'method': 'bank_transfer',
    'min_order_amount': 10,
    'min_order_amount_display': '10.00',
    'description': 'Please contact via whatsapp 1234',
    'offer_id': '8',
    'price': 13500,
    'price_display': '13500',
    'rate': 13500,
    'rate_display': '13500',
    'type': 'sell'
  },
  <String, dynamic>{
    'account_currency': 'USD',
    'agent_id': '2',
    'agent_name': 'mock_name',
    'amount': 100,
    'amount_display': '100.00',
    'amount_used': 0,
    'amount_used_display': '0.00',
    'country': 'id',
    'created_time': 1577156519,
    'is_active': 1,
    'local_currency': 'IDR',
    'max_order_amount': 100,
    'max_order_amount_display': '100.00',
    'method': 'bank_transfer',
    'min_order_amount': 10,
    'min_order_amount_display': '10.00',
    'description': 'Please contact via whatsapp 1234',
    'offer_id': '4',
    'price': 13500,
    'price_display': '13500',
    'rate': 13500,
    'rate_display': '13500',
    'type': 'sell'
  },
  <String, dynamic>{
    'account_currency': 'USD',
    'agent_id': '3',
    'agent_name': 'mock_mun agent',
    'amount': 100,
    'amount_display': '100.00',
    'amount_used': 0,
    'amount_used_display': '0.00',
    'country': 'id',
    'created_time': 1577156942,
    'is_active': 1,
    'local_currency': 'IDR',
    'max_order_amount': 100,
    'max_order_amount_display': '100.00',
    'method': 'bank_transfer',
    'min_order_amount': 10,
    'min_order_amount_display': '10.00',
    'description': 'Please contact via whatsapp 1234',
    'offer_id': '6',
    'price': 13500,
    'price_display': '13500',
    'rate': 13500,
    'rate_display': '13500',
    'type': 'sell'
  },
  <String, dynamic>{
    'account_currency': 'USD',
    'agent_id': '5',
    'agent_name': 'mock_name',
    'amount': 100,
    'amount_display': '100.00',
    'amount_used': 0,
    'amount_used_display': '0.00',
    'country': 'id',
    'created_time': 1577167966,
    'is_active': 1,
    'local_currency': 'IDR',
    'max_order_amount': 100,
    'max_order_amount_display': '100.00',
    'method': 'bank_transfer',
    'min_order_amount': 10,
    'min_order_amount_display': '10.00',
    'description': 'Please contact via whatsapp 1234',
    'offer_id': '10',
    'price': 13500,
    'price_display': '13500',
    'rate': 13500,
    'rate_display': '13500',
    'type': 'sell'
  },
  <String, dynamic>{
    'account_currency': 'USD',
    'agent_id': '1',
    'agent_name': 'mock_where is water',
    'amount': 100,
    'amount_display': '100.00',
    'amount_used': 0,
    'amount_used_display': '0.00',
    'country': 'id',
    'created_time': 1577155730,
    'is_active': 1,
    'local_currency': 'IDR',
    'max_order_amount': 100,
    'max_order_amount_display': '100.00',
    'method': 'bank_transfer',
    'min_order_amount': 10,
    'min_order_amount_display': '10.00',
    'description': 'Please contact via whatsapp 1234',
    'offer_id': '2',
    'price': 13500,
    'price_display': '13500',
    'rate': 13500,
    'rate_display': '13500',
    'type': 'sell'
  }
];
