// AUTO-GENERATED - DO NOT MODIFY BY HAND
// Auto generated from 1st step of the flutter_deriv_api code generation process
// uses collected `msg_type`s from the 1st step to create a helper
// function that maps the `msg_type`s to equivalent Response objects

import 'package:flutter_deriv_api/basic_api/generated/api.dart';

import '../response.dart';

/// A function that create a sub-type of [Response] based on
/// [responseMap]'s 'msg_type'
Response getGeneratedResponse(Map<String, dynamic> responseMap) {
  switch (responseMap['msg_type']) {
    case 'account_list':
      return AccountListReceive.fromJson(responseMap);
    case 'active_symbols':
      return ActiveSymbolsReceive.fromJson(responseMap);
    case 'api_token':
      return ApiTokenReceive.fromJson(responseMap);
    case 'app_delete':
      return AppDeleteReceive.fromJson(responseMap);
    case 'app_get':
      return AppGetReceive.fromJson(responseMap);
    case 'app_list':
      return AppListReceive.fromJson(responseMap);
    case 'app_markup_details':
      return AppMarkupDetailsReceive.fromJson(responseMap);
    case 'app_markup_statistics':
      return AppMarkupStatisticsReceive.fromJson(responseMap);
    case 'app_register':
      return AppRegisterReceive.fromJson(responseMap);
    case 'app_update':
      return AppUpdateReceive.fromJson(responseMap);
    case 'asset_index':
      return AssetIndexReceive.fromJson(responseMap);
    case 'authorize':
      return AuthorizeReceive.fromJson(responseMap);
    case 'balance':
      return BalanceReceive.fromJson(responseMap);
    case 'buy_contract_for_multiple_accounts':
      return BuyContractForMultipleAccountsReceive.fromJson(responseMap);
    case 'buy':
      return BuyReceive.fromJson(responseMap);
    case 'cancel':
      return CancelReceive.fromJson(responseMap);
    case 'cashier':
      return CashierReceive.fromJson(responseMap);
    case 'confirm_email':
      return ConfirmEmailReceive.fromJson(responseMap);
    case 'contract_update_history':
      return ContractUpdateHistoryReceive.fromJson(responseMap);
    case 'contract_update':
      return ContractUpdateReceive.fromJson(responseMap);
    case 'contracts_for':
      return ContractsForReceive.fromJson(responseMap);
    case 'copy_start':
      return CopyStartReceive.fromJson(responseMap);
    case 'copy_stop':
      return CopyStopReceive.fromJson(responseMap);
    case 'copytrading_list':
      return CopytradingListReceive.fromJson(responseMap);
    case 'copytrading_statistics':
      return CopytradingStatisticsReceive.fromJson(responseMap);
    case 'crypto_config':
      return CryptoConfigReceive.fromJson(responseMap);
    case 'crypto_estimations':
      return CryptoEstimationsReceive.fromJson(responseMap);
    case 'document_upload':
      return DocumentUploadReceive.fromJson(responseMap);
    case 'economic_calendar':
      return EconomicCalendarReceive.fromJson(responseMap);
    case 'exchange_rates':
      return ExchangeRatesReceive.fromJson(responseMap);
    case 'forget_all':
      return ForgetAllReceive.fromJson(responseMap);
    case 'forget':
      return ForgetReceive.fromJson(responseMap);
    case 'get_financial_assessment':
      return GetFinancialAssessmentReceive.fromJson(responseMap);
    case 'get_limits':
      return GetLimitsReceive.fromJson(responseMap);
    case 'get_self_exclusion':
      return GetSelfExclusionReceive.fromJson(responseMap);
    case 'get_settings':
      return GetSettingsReceive.fromJson(responseMap);
    case 'identity_verification_document_add':
      return IdentityVerificationDocumentAddReceive.fromJson(responseMap);
    case 'kyc_auth_status':
      return KycAuthStatusReceive.fromJson(responseMap);
    case 'landing_company_details':
      return LandingCompanyDetailsReceive.fromJson(responseMap);
    case 'landing_company':
      return LandingCompanyReceive.fromJson(responseMap);
    case 'login_history':
      return LoginHistoryReceive.fromJson(responseMap);
    case 'logout':
      return LogoutReceive.fromJson(responseMap);
    case 'mt5_deposit':
      return Mt5DepositReceive.fromJson(responseMap);
    case 'mt5_get_settings':
      return Mt5GetSettingsReceive.fromJson(responseMap);
    case 'mt5_login_list':
      return Mt5LoginListReceive.fromJson(responseMap);
    case 'mt5_new_account':
      return Mt5NewAccountReceive.fromJson(responseMap);
    case 'mt5_password_change':
      return Mt5PasswordChangeReceive.fromJson(responseMap);
    case 'mt5_password_check':
      return Mt5PasswordCheckReceive.fromJson(responseMap);
    case 'mt5_password_reset':
      return Mt5PasswordResetReceive.fromJson(responseMap);
    case 'mt5_withdrawal':
      return Mt5WithdrawalReceive.fromJson(responseMap);
    case 'new_account_maltainvest':
      return NewAccountMaltainvestReceive.fromJson(responseMap);
    case 'new_account_real':
      return NewAccountRealReceive.fromJson(responseMap);
    case 'new_account_virtual':
      return NewAccountVirtualReceive.fromJson(responseMap);
    case 'oauth_apps':
      return OauthAppsReceive.fromJson(responseMap);
    case 'p2p_advert_create':
      return P2pAdvertCreateReceive.fromJson(responseMap);
    case 'p2p_advert_info':
      return P2pAdvertInfoReceive.fromJson(responseMap);
    case 'p2p_advert_list':
      return P2pAdvertListReceive.fromJson(responseMap);
    case 'p2p_advert_update':
      return P2pAdvertUpdateReceive.fromJson(responseMap);
    case 'p2p_advertiser_adverts':
      return P2pAdvertiserAdvertsReceive.fromJson(responseMap);
    case 'p2p_advertiser_create':
      return P2pAdvertiserCreateReceive.fromJson(responseMap);
    case 'p2p_advertiser_info':
      return P2pAdvertiserInfoReceive.fromJson(responseMap);
    case 'p2p_advertiser_list':
      return P2pAdvertiserListReceive.fromJson(responseMap);
    case 'p2p_advertiser_payment_methods':
      return P2pAdvertiserPaymentMethodsReceive.fromJson(responseMap);
    case 'p2p_advertiser_relations':
      return P2pAdvertiserRelationsReceive.fromJson(responseMap);
    case 'p2p_advertiser_update':
      return P2pAdvertiserUpdateReceive.fromJson(responseMap);
    case 'p2p_chat_create':
      return P2pChatCreateReceive.fromJson(responseMap);
    case 'p2p_order_cancel':
      return P2pOrderCancelReceive.fromJson(responseMap);
    case 'p2p_order_confirm':
      return P2pOrderConfirmReceive.fromJson(responseMap);
    case 'p2p_order_create':
      return P2pOrderCreateReceive.fromJson(responseMap);
    case 'p2p_order_dispute':
      return P2pOrderDisputeReceive.fromJson(responseMap);
    case 'p2p_order_info':
      return P2pOrderInfoReceive.fromJson(responseMap);
    case 'p2p_order_list':
      return P2pOrderListReceive.fromJson(responseMap);
    case 'p2p_order_review':
      return P2pOrderReviewReceive.fromJson(responseMap);
    case 'p2p_payment_methods':
      return P2pPaymentMethodsReceive.fromJson(responseMap);
    case 'p2p_ping':
      return P2pPingReceive.fromJson(responseMap);
    case 'p2p_settings':
      return P2pSettingsReceive.fromJson(responseMap);
    case 'payment_methods':
      return PaymentMethodsReceive.fromJson(responseMap);
    case 'paymentagent_create':
      return PaymentagentCreateReceive.fromJson(responseMap);
    case 'paymentagent_details':
      return PaymentagentDetailsReceive.fromJson(responseMap);
    case 'paymentagent_list':
      return PaymentagentListReceive.fromJson(responseMap);
    case 'paymentagent_transfer':
      return PaymentagentTransferReceive.fromJson(responseMap);
    case 'paymentagent_withdraw_justification':
      return PaymentagentWithdrawJustificationReceive.fromJson(responseMap);
    case 'paymentagent_withdraw':
      return PaymentagentWithdrawReceive.fromJson(responseMap);
    case 'payout_currencies':
      return PayoutCurrenciesReceive.fromJson(responseMap);
    case 'ping':
      return PingReceive.fromJson(responseMap);
    case 'portfolio':
      return PortfolioReceive.fromJson(responseMap);
    case 'profit_table':
      return ProfitTableReceive.fromJson(responseMap);
    case 'proposal_open_contract':
      return ProposalOpenContractReceive.fromJson(responseMap);
    case 'proposal':
      return ProposalReceive.fromJson(responseMap);
    case 'reality_check':
      return RealityCheckReceive.fromJson(responseMap);
    case 'residence_list':
      return ResidenceListReceive.fromJson(responseMap);
    case 'revoke_oauth_app':
      return RevokeOauthAppReceive.fromJson(responseMap);
    case 'sell_contract_for_multiple_accounts':
      return SellContractForMultipleAccountsReceive.fromJson(responseMap);
    case 'sell_expired':
      return SellExpiredReceive.fromJson(responseMap);
    case 'sell':
      return SellReceive.fromJson(responseMap);
    case 'set_account_currency':
      return SetAccountCurrencyReceive.fromJson(responseMap);
    case 'set_financial_assessment':
      return SetFinancialAssessmentReceive.fromJson(responseMap);
    case 'set_self_exclusion':
      return SetSelfExclusionReceive.fromJson(responseMap);
    case 'set_settings':
      return SetSettingsReceive.fromJson(responseMap);
    case 'statement':
      return StatementReceive.fromJson(responseMap);
    case 'states_list':
      return StatesListReceive.fromJson(responseMap);
    case 'history':
      return TicksHistoryReceive.fromJson(responseMap);
    case 'tick':
      return TicksReceive.fromJson(responseMap);
    case 'time':
      return TimeReceive.fromJson(responseMap);
    case 'tnc_approval':
      return TncApprovalReceive.fromJson(responseMap);
    case 'topup_virtual':
      return TopupVirtualReceive.fromJson(responseMap);
    case 'trading_durations':
      return TradingDurationsReceive.fromJson(responseMap);
    case 'trading_platform_investor_password_reset':
      return TradingPlatformInvestorPasswordResetReceive.fromJson(responseMap);
    case 'trading_platform_password_reset':
      return TradingPlatformPasswordResetReceive.fromJson(responseMap);
    case 'trading_servers':
      return TradingServersReceive.fromJson(responseMap);
    case 'trading_times':
      return TradingTimesReceive.fromJson(responseMap);
    case 'transaction':
      return TransactionReceive.fromJson(responseMap);
    case 'transfer_between_accounts':
      return TransferBetweenAccountsReceive.fromJson(responseMap);
    case 'unsubscribe_email':
      return UnsubscribeEmailReceive.fromJson(responseMap);
    case 'verify_email_cellxpert':
      return VerifyEmailCellxpertReceive.fromJson(responseMap);
    case 'verify_email':
      return VerifyEmailReceive.fromJson(responseMap);
    case 'website_config':
      return WebsiteConfigReceive.fromJson(responseMap);
    case 'website_status':
      return WebsiteStatusReceive.fromJson(responseMap);
    case 'get_account_status':
      return GetAccountStatusReceive.fromJson(responseMap);

    default:
      return Response.fromJson(responseMap);
  }
}
