const String activeSymbolsJson = '''{
  "active_symbols": [
    {
      "allow_forward_starting": 0,
      "display_name": "AUD Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.001,
      "submarket": "smart_fx",
      "submarket_display_name": "Smart FX",
      "symbol": "WLDAUD",
      "symbol_type": "smart_fx"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "AUD/CAD",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "minor_pairs",
      "submarket_display_name": "Minor Pairs",
      "symbol": "frxAUDCAD",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "AUD/CHF",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "minor_pairs",
      "submarket_display_name": "Minor Pairs",
      "symbol": "frxAUDCHF",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "AUD/JPY",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.001,
      "submarket": "major_pairs",
      "submarket_display_name": "Major Pairs",
      "symbol": "frxAUDJPY",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "AUD/NZD",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "minor_pairs",
      "submarket_display_name": "Minor Pairs",
      "symbol": "frxAUDNZD",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "AUD/USD",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "major_pairs",
      "submarket_display_name": "Major Pairs",
      "symbol": "frxAUDUSD",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "Australian Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "indices",
      "market_display_name": "Stock Indices",
      "pip": 0.01,
      "submarket": "asia_oceania_OTC",
      "submarket_display_name": "Asia/Oceania",
      "symbol": "OTC_AS51",
      "symbol_type": "stockindex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "Bear Market Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "synthetic_index",
      "market_display_name": "Synthetic Indices",
      "pip": 0.0001,
      "submarket": "random_daily",
      "submarket_display_name": "Daily Reset Indices",
      "symbol": "RDBEAR",
      "symbol_type": "stockindex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "Bull Market Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "synthetic_index",
      "market_display_name": "Synthetic Indices",
      "pip": 0.0001,
      "submarket": "random_daily",
      "submarket_display_name": "Daily Reset Indices",
      "symbol": "RDBULL",
      "symbol_type": "stockindex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "Dutch Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "indices",
      "market_display_name": "Stock Indices",
      "pip": 0.01,
      "submarket": "europe_OTC",
      "submarket_display_name": "Europe",
      "symbol": "OTC_AEX",
      "symbol_type": "stockindex"
    },
    {
      "allow_forward_starting": 0,
      "display_name": "EUR Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.001,
      "submarket": "smart_fx",
      "submarket_display_name": "Smart FX",
      "symbol": "WLDEUR",
      "symbol_type": "smart_fx"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "EUR/AUD",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "major_pairs",
      "submarket_display_name": "Major Pairs",
      "symbol": "frxEURAUD",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "EUR/CAD",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "major_pairs",
      "submarket_display_name": "Major Pairs",
      "symbol": "frxEURCAD",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "EUR/CHF",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "major_pairs",
      "submarket_display_name": "Major Pairs",
      "symbol": "frxEURCHF",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "EUR/GBP",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "major_pairs",
      "submarket_display_name": "Major Pairs",
      "symbol": "frxEURGBP",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "EUR/JPY",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.001,
      "submarket": "major_pairs",
      "submarket_display_name": "Major Pairs",
      "symbol": "frxEURJPY",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "EUR/NZD",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "minor_pairs",
      "submarket_display_name": "Minor Pairs",
      "symbol": "frxEURNZD",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "EUR/USD",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "major_pairs",
      "submarket_display_name": "Major Pairs",
      "symbol": "frxEURUSD",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "Euro 50 Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "indices",
      "market_display_name": "Stock Indices",
      "pip": 0.01,
      "submarket": "europe_OTC",
      "submarket_display_name": "Europe",
      "symbol": "OTC_SX5E",
      "symbol_type": "stockindex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "French Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "indices",
      "market_display_name": "Stock Indices",
      "pip": 0.01,
      "submarket": "europe_OTC",
      "submarket_display_name": "Europe",
      "symbol": "OTC_FCHI",
      "symbol_type": "stockindex"
    },
    {
      "allow_forward_starting": 0,
      "display_name": "GBP Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.001,
      "submarket": "smart_fx",
      "submarket_display_name": "Smart FX",
      "symbol": "WLDGBP",
      "symbol_type": "smart_fx"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "GBP/AUD",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "major_pairs",
      "submarket_display_name": "Major Pairs",
      "symbol": "frxGBPAUD",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "GBP/CAD",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "minor_pairs",
      "submarket_display_name": "Minor Pairs",
      "symbol": "frxGBPCAD",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "GBP/CHF",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "minor_pairs",
      "submarket_display_name": "Minor Pairs",
      "symbol": "frxGBPCHF",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "GBP/JPY",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.001,
      "submarket": "major_pairs",
      "submarket_display_name": "Major Pairs",
      "symbol": "frxGBPJPY",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "GBP/NOK",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "minor_pairs",
      "submarket_display_name": "Minor Pairs",
      "symbol": "frxGBPNOK",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "GBP/NZD",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "minor_pairs",
      "submarket_display_name": "Minor Pairs",
      "symbol": "frxGBPNZD",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "GBP/USD",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "major_pairs",
      "submarket_display_name": "Major Pairs",
      "symbol": "frxGBPUSD",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "German Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "indices",
      "market_display_name": "Stock Indices",
      "pip": 0.01,
      "submarket": "europe_OTC",
      "submarket_display_name": "Europe",
      "symbol": "OTC_GDAXI",
      "symbol_type": "stockindex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "Gold/USD",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "commodities",
      "market_display_name": "Commodities",
      "pip": 0.01,
      "submarket": "metals",
      "submarket_display_name": "Metals",
      "symbol": "frxXAUUSD",
      "symbol_type": "commodities"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "Hong Kong Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "indices",
      "market_display_name": "Stock Indices",
      "pip": 0.01,
      "submarket": "asia_oceania_OTC",
      "submarket_display_name": "Asia/Oceania",
      "symbol": "OTC_HSI",
      "symbol_type": "stockindex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "Japanese Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "indices",
      "market_display_name": "Stock Indices",
      "pip": 0.01,
      "submarket": "asia_oceania_OTC",
      "submarket_display_name": "Asia/Oceania",
      "symbol": "OTC_N225",
      "symbol_type": "stockindex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "NZD/JPY",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.001,
      "submarket": "minor_pairs",
      "submarket_display_name": "Minor Pairs",
      "symbol": "frxNZDJPY",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "NZD/USD",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "minor_pairs",
      "submarket_display_name": "Minor Pairs",
      "symbol": "frxNZDUSD",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "Oil/USD",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "commodities",
      "market_display_name": "Commodities",
      "pip": 0.01,
      "submarket": "energy",
      "submarket_display_name": "Energy",
      "symbol": "frxBROUSD",
      "symbol_type": "commodities"
    },
    {
      "allow_forward_starting": 0,
      "display_name": "Palladium/USD",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "commodities",
      "market_display_name": "Commodities",
      "pip": 0.01,
      "submarket": "metals",
      "submarket_display_name": "Metals",
      "symbol": "frxXPDUSD",
      "symbol_type": "commodities"
    },
    {
      "allow_forward_starting": 0,
      "display_name": "Platinum/USD",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "commodities",
      "market_display_name": "Commodities",
      "pip": 0.01,
      "submarket": "metals",
      "submarket_display_name": "Metals",
      "symbol": "frxXPTUSD",
      "symbol_type": "commodities"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "Silver/USD",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "commodities",
      "market_display_name": "Commodities",
      "pip": 0.0001,
      "submarket": "metals",
      "submarket_display_name": "Metals",
      "symbol": "frxXAGUSD",
      "symbol_type": "commodities"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "Swiss Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "indices",
      "market_display_name": "Stock Indices",
      "pip": 0.01,
      "submarket": "europe_OTC",
      "submarket_display_name": "Europe",
      "symbol": "OTC_SSMI",
      "symbol_type": "stockindex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "UK Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "indices",
      "market_display_name": "Stock Indices",
      "pip": 0.01,
      "submarket": "europe_OTC",
      "submarket_display_name": "Europe",
      "symbol": "OTC_FTSE",
      "symbol_type": "stockindex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "US Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "indices",
      "market_display_name": "Stock Indices",
      "pip": 0.01,
      "submarket": "americas_OTC",
      "submarket_display_name": "Americas",
      "symbol": "OTC_SPC",
      "symbol_type": "stockindex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "US Tech Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "indices",
      "market_display_name": "Stock Indices",
      "pip": 0.01,
      "submarket": "americas_OTC",
      "submarket_display_name": "Americas",
      "symbol": "OTC_NDX",
      "symbol_type": "stockindex"
    },
    {
      "allow_forward_starting": 0,
      "display_name": "USD Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.001,
      "submarket": "smart_fx",
      "submarket_display_name": "Smart FX",
      "symbol": "WLDUSD",
      "symbol_type": "smart_fx"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "USD/CAD",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "major_pairs",
      "submarket_display_name": "Major Pairs",
      "symbol": "frxUSDCAD",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "USD/CHF",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "major_pairs",
      "submarket_display_name": "Major Pairs",
      "symbol": "frxUSDCHF",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "USD/JPY",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.001,
      "submarket": "major_pairs",
      "submarket_display_name": "Major Pairs",
      "symbol": "frxUSDJPY",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "USD/MXN",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.0001,
      "submarket": "minor_pairs",
      "submarket_display_name": "Minor Pairs",
      "symbol": "frxUSDMXN",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "USD/NOK",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "minor_pairs",
      "submarket_display_name": "Minor Pairs",
      "symbol": "frxUSDNOK",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "USD/PLN",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.0001,
      "submarket": "minor_pairs",
      "submarket_display_name": "Minor Pairs",
      "symbol": "frxUSDPLN",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "USD/SEK",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "submarket": "minor_pairs",
      "submarket_display_name": "Minor Pairs",
      "symbol": "frxUSDSEK",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "Volatility 10 (1s) Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "synthetic_index",
      "market_display_name": "Synthetic Indices",
      "pip": 0.01,
      "submarket": "random_index",
      "submarket_display_name": "Continuous Indices",
      "symbol": "1HZ10V",
      "symbol_type": "stockindex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "Volatility 10 Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "synthetic_index",
      "market_display_name": "Synthetic Indices",
      "pip": 0.001,
      "submarket": "random_index",
      "submarket_display_name": "Continuous Indices",
      "symbol": "R_10",
      "symbol_type": "stockindex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "Volatility 25 Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "synthetic_index",
      "market_display_name": "Synthetic Indices",
      "pip": 0.001,
      "submarket": "random_index",
      "submarket_display_name": "Continuous Indices",
      "symbol": "R_25",
      "symbol_type": "stockindex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "Volatility 50 Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "synthetic_index",
      "market_display_name": "Synthetic Indices",
      "pip": 0.0001,
      "submarket": "random_index",
      "submarket_display_name": "Continuous Indices",
      "symbol": "R_50",
      "symbol_type": "stockindex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "Volatility 75 Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "synthetic_index",
      "market_display_name": "Synthetic Indices",
      "pip": 0.0001,
      "submarket": "random_index",
      "submarket_display_name": "Continuous Indices",
      "symbol": "R_75",
      "symbol_type": "stockindex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "Volatility 100 (1s) Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "synthetic_index",
      "market_display_name": "Synthetic Indices",
      "pip": 0.01,
      "submarket": "random_index",
      "submarket_display_name": "Continuous Indices",
      "symbol": "1HZ100V",
      "symbol_type": "stockindex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "Volatility 100 Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "synthetic_index",
      "market_display_name": "Synthetic Indices",
      "pip": 0.01,
      "submarket": "random_index",
      "submarket_display_name": "Continuous Indices",
      "symbol": "R_100",
      "symbol_type": "stockindex"
    },
    {
      "allow_forward_starting": 1,
      "display_name": "Wall Street Index",
      "exchange_is_open": 1,
      "is_trading_suspended": 0,
      "market": "indices",
      "market_display_name": "Stock Indices",
      "pip": 0.01,
      "submarket": "americas_OTC",
      "submarket_display_name": "Americas",
      "symbol": "OTC_DJI",
      "symbol_type": "stockindex"
    }
  ],
  "echo_req": {
    "active_symbols": "brief",
    "product_type": "basic"
  },
  "msg_type": "active_symbols"
}''';