const String activeSymbolsJson = '''{
  "active_symbols": [
    {
      "allow_forward_starting": 0,
      "delay_amount": 0,
      "display_name": "AUD Index",
      "exchange_is_open": 1,
      "exchange_name": "FOREX",
      "intraday_interval_minutes": 5,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.001,
      "quoted_currency_symbol": "WLDAUD",
      "spot": 808.243,
      "spot_age": "1",
      "spot_time": "1586926361",
      "submarket": "smart_fx",
      "submarket_display_name": "Smart FX",
      "symbol": "WLDAUD",
      "symbol_type": "smart_fx"
    },
    {
      "allow_forward_starting": 1,
      "delay_amount": 0,
      "display_name": "AUD/CAD",
      "exchange_name": "FOREX",
      "intraday_interval_minutes": 5,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "quoted_currency_symbol": "CAD",
      "spot": 0.8905,
      "spot_age": "1",
      "spot_time": "1586926361",
      "submarket": "minor_pairs",
      "submarket_display_name": "Minor Pairs",
      "symbol": "frxAUDCAD",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "delay_amount": 0,
      "display_name": "AUD/CHF",
      "exchange_is_open": 1,
      "exchange_name": "FOREX",
      "intraday_interval_minutes": 5,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "quoted_currency_symbol": "CHF",
      "spot": 0.61543,
      "spot_age": "1",
      "spot_time": "1586926361",
      "submarket": "minor_pairs",
      "submarket_display_name": "Minor Pairs",
      "symbol": "frxAUDCHF",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "delay_amount": 0,
      "display_name": "AUD/JPY",
      "exchange_is_open": 1,
      "exchange_name": "FOREX",
      "intraday_interval_minutes": 5,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.001,
      "quoted_currency_symbol": "JPY",
      "spot": 68.571,
      "spot_age": "0",
      "spot_time": "1586926362",
      "submarket": "major_pairs",
      "submarket_display_name": "Major Pairs",
      "symbol": "frxAUDJPY",
      "symbol_type": "forex"
    },
    {
      "allow_forward_starting": 1,
      "delay_amount": 0,
      "display_name": "AUD/NZD",
      "exchange_is_open": 1,
      "exchange_name": "FOREX",
      "intraday_interval_minutes": 5,
      "is_trading_suspended": 0,
      "market": "forex",
      "market_display_name": "Forex",
      "pip": 0.00001,
      "quoted_currency_symbol": "NZD",
      "spot": 1.05581,
      "spot_age": "1",
      "spot_time": "1586926361",
      "submarket": "minor_pairs",
      "submarket_display_name": "Minor Pairs",
      "symbol": "frxAUDNZD",
      "symbol_type": "forex"
    }
  ],
  "echo_req": {
    "active_symbols": "full",
    "product_type": "basic"
  },
  "msg_type": "active_symbols"
}''';